/**
 * Which provenance signals one uploaded file gets, and which it deliberately does
 * not (#1015 W8).
 *
 * `fingerprint.ts` and `preview-hash.ts` answer *"can this be fingerprinted?"*.
 * This module answers the different question *"should it be?"* — and the two
 * exclusions below are the whole of its value, because a fingerprint on the wrong
 * kind of file is not a weak signal, it is a machine that opens moderation reviews
 * against creators who did nothing.
 *
 * Everything here is still PURE: bytes in, signals out. `recordDerivedSignals`
 * is the one function that writes, and it is separate so the decision and the
 * persistence can be tested apart.
 */

import type { AssetFileRole, AssetProvenanceSignalKind } from '@mercaria/shared-types';
import { assetFormatCapability } from '@mercaria/shared-types';
import { recordProvenanceSignal } from '../../../db/digital/assetRepository.js';
import type { DatabaseOrTransaction } from '../../../db/postgres.js';
import { contentHash, geometryFingerprint } from './fingerprint.js';
import { previewPerceptualHash, type PreviewRaster } from './preview-hash.js';

/**
 * The file roles whose bytes are hashed as provenance evidence.
 *
 * Six of the eight in `ASSET_FILE_ROLES`. The two omissions are the point:
 *
 * - **`documentation`** — a readme, a printing-notes page and above all a LICENCE
 *   TEXT. Thousands of unrelated creators ship byte-identical copies of the same
 *   Creative Commons text, and a content-hash match on one is a re-upload
 *   accusation generated by two people obeying the same licence.
 * - **`profile`** — a slicer or engine profile. Creators share, fork and re-export
 *   these deliberately; an identical `.ini` for the same printer is a compatible
 *   profile, not a copied work.
 *
 * Stated as a closed list rather than as a filter on "the big files", because the
 * distinction is about what the bytes MEAN and a size heuristic would let a large
 * shared licence pack through while excluding a small texture.
 */
export const PROVENANCE_HASHED_FILE_ROLES: readonly AssetFileRole[] = [
  'source',
  'mesh',
  'texture',
  'preview',
  'web_derivative',
  'archive',
];

/**
 * The smallest file that gets a content hash as EVIDENCE.
 *
 * One kibibyte. Below it a file is a stub, a placeholder, an empty archive, a
 * one-line manifest or a 1×1 transparent PNG — and byte-identical stubs are what
 * every export pipeline produces, not what a copied work looks like. The bound is
 * on the evidence only: `asset_files.content_hash` is still computed for every
 * file, because THAT one is an integrity record rather than a provenance claim.
 */
export const PROVENANCE_MIN_HASHED_BYTES = 1024;

/** One signal ready to be recorded. */
export interface DerivedProvenanceSignal {
  readonly kind: AssetProvenanceSignalKind;
  readonly value: string;
}

/**
 * A fingerprint that was NOT derived, with the reason.
 *
 * Returned rather than dropped, because #1015 W4's rule — *do not overclaim
 * machine-generated validation* — has an exact counterpart here: a sweep that found
 * nothing because nothing was fingerprinted is a completely different statement
 * from a sweep that found nothing because nothing matched, and only one of them
 * should reassure anybody.
 */
export interface UnderivedProvenanceSignal {
  readonly kind: AssetProvenanceSignalKind;
  readonly reason: string;
}

export interface DeriveFileSignalsInput {
  readonly formatKey: string;
  readonly role: AssetFileRole;
  readonly bytes: Uint8Array;
  /**
   * The raster of the preview Mercaria GENERATED for this file, when there is
   * one. Never a decode of the creator's bytes — see `preview-hash.ts`.
   */
  readonly generatedPreview?: PreviewRaster;
}

export interface DerivedFileSignals {
  readonly derived: readonly DerivedProvenanceSignal[];
  readonly underived: readonly UnderivedProvenanceSignal[];
}

/**
 * Every provenance signal one file yields.
 *
 * Note what this never returns: a match, a candidate, a score or a conclusion. It
 * produces evidence, and `sweep.ts` is the only thing that compares any of it.
 */
export function deriveFileProvenanceSignals(input: DeriveFileSignalsInput): DerivedFileSignals {
  const derived: DerivedProvenanceSignal[] = [];
  const underived: UnderivedProvenanceSignal[] = [];

  if (!PROVENANCE_HASHED_FILE_ROLES.includes(input.role)) {
    underived.push({ kind: 'content_hash', reason: `role_not_hashed:${input.role}` });
  } else if (input.bytes.byteLength < PROVENANCE_MIN_HASHED_BYTES) {
    underived.push({ kind: 'content_hash', reason: 'below_minimum_hashed_bytes' });
  } else {
    derived.push({ kind: 'content_hash', value: contentHash(input.bytes) });
  }

  const capability = assetFormatCapability(input.formatKey);
  if (capability?.geometryMeasurable === true) {
    const geometry = geometryFingerprint(input.formatKey, input.bytes);
    if (geometry.status === 'derived') {
      derived.push({ kind: 'geometry_fingerprint', value: geometry.value });
    } else {
      underived.push({ kind: 'geometry_fingerprint', reason: geometry.reason });
    }
  } else {
    underived.push({
      kind: 'geometry_fingerprint',
      reason: capability === undefined ? 'unknown_format' : 'format_not_geometry_measurable',
    });
  }

  if (input.generatedPreview !== undefined) {
    const preview = previewPerceptualHash(input.generatedPreview);
    if (preview.status === 'derived') {
      derived.push({ kind: 'preview_phash', value: preview.value });
    } else {
      underived.push({ kind: 'preview_phash', reason: preview.reason });
    }
  }

  return { derived, underived };
}

/**
 * Append the derived signals to `asset_provenance_signals`.
 *
 * Straight through to the repository, which is `ON CONFLICT DO NOTHING` on the
 * whole identity tuple and has no update path — the table is append-only by
 * trigger for published versions, so re-running a derivation converges instead of
 * growing the evidence or rewriting it.
 *
 * There is deliberately no "clear the signals for this file" here, and there must
 * never be one: a creator able to erase the fingerprint of something they
 * published is the shape `asset_provenance_signals_append_only` exists to refuse.
 */
export async function recordDerivedSignals(
  input: {
    readonly versionId: string;
    readonly fileId: string | null;
    readonly signals: readonly DerivedProvenanceSignal[];
  },
  tx?: DatabaseOrTransaction,
): Promise<void> {
  for (const signal of input.signals) {
    await recordProvenanceSignal(
      {
        versionId: input.versionId,
        fileId: input.fileId,
        kind: signal.kind,
        value: signal.value,
      },
      tx,
    );
  }
}
