/**
 * Reads and writes on `guest_sessions` (ADR 0003 D3, #103).
 *
 * Every mutation here is ONE conditional statement (`UPDATE … WHERE …
 * RETURNING`), the `CONVENTIONS.md` concurrency rule: the row is locked for
 * the statement and the loser's predicate is re-checked against the winner's
 * write, so two concurrent rotations produce exactly one rotation and two
 * concurrent revocations exactly one `revoked_at`. A read-then-write here
 * would be a lost-update bug wearing the same signature.
 *
 * The repository knows nothing about tokens — it stores and matches HASHES a
 * service computed. The plaintext credential never reaches this module, so it
 * cannot end up in a query log.
 */

import { and, eq, gt, isNull, lt, or } from 'drizzle-orm';
import type { GuestClientClass } from '@mercaria/shared-types';
import { guestSessions } from '../schema/guests.js';
import type { DatabaseOrTransaction } from '../postgres.js';

/** A guest session row as every caller reads it. */
export type GuestSessionRow = typeof guestSessions.$inferSelect;

/** What issuance writes. The id is generated by the schema's uuid v7 default. */
export interface InsertGuestSessionInput {
  /** Hex SHA-256 of the freshly minted token. NEVER the plaintext. */
  tokenHash: string;
  clientClass: GuestClientClass;
  /** The ABSOLUTE deadline (now + `GUEST_SESSION_ABSOLUTE_DAYS`). */
  expiresAt: Date;
  lastSeenAt: Date;
}

/** Create a session row. The unique hash index makes a duplicate impossible. */
export async function insertGuestSession(
  db: DatabaseOrTransaction,
  input: InsertGuestSessionInput,
): Promise<GuestSessionRow> {
  const [row] = await db
    .insert(guestSessions)
    .values({
      tokenHash: input.tokenHash,
      clientClass: input.clientClass,
      expiresAt: input.expiresAt,
      lastSeenAt: input.lastSeenAt,
    })
    .returning();
  if (!row) {
    // `.returning()` on a plain INSERT yields exactly one row or throws before
    // this point; the guard exists so the return type needs no `!`.
    throw new Error('insertGuestSession returned no row');
  }
  return row;
}

/**
 * Resolve a presented hash to its session, honouring the rotation grace.
 *
 * ONE query, two indexed predicates BitmapOr'd: the current-hash unique index
 * (the common path) and the partial previous-hash index (a 60-second window
 * after a rotation). Which one matched is the CALLER's question — it compares
 * `row.tokenHash` against what it presented — so this stays a pure lookup.
 *
 * Liveness (expiry, revocation, idle) is deliberately NOT filtered here: the
 * service decides it, in one place, so the resolver and the inspect surface
 * cannot drift on what "live" means.
 */
export async function findGuestSessionByTokenHash(
  db: DatabaseOrTransaction,
  tokenHash: string,
  now: Date,
): Promise<GuestSessionRow | undefined> {
  const [row] = await db
    .select()
    .from(guestSessions)
    .where(
      or(
        eq(guestSessions.tokenHash, tokenHash),
        and(
          eq(guestSessions.previousTokenHash, tokenHash),
          gt(guestSessions.previousTokenExpiresAt, now),
        ),
      ),
    )
    .limit(1);
  return row;
}

/**
 * Advance `last_seen_at`, but only when the stored value is at least
 * `granularityMs` stale — the D3 write-amplification bound. A request inside
 * the granularity window writes nothing at all.
 *
 * @returns Whether a write happened (a test hook; callers ignore it).
 */
export async function touchGuestSessionLastSeen(
  db: DatabaseOrTransaction,
  id: string,
  now: Date,
  granularityMs: number,
): Promise<boolean> {
  const updated = await db
    .update(guestSessions)
    .set({ lastSeenAt: now })
    .where(
      and(
        eq(guestSessions.id, id),
        lt(guestSessions.lastSeenAt, new Date(now.getTime() - granularityMs)),
      ),
    )
    .returning({ id: guestSessions.id });
  return updated.length === 1;
}

/** What a rotation swaps in. */
export interface RotateGuestSessionInput {
  id: string;
  /** The hash the caller RESOLVED with — the CAS guard. */
  currentTokenHash: string;
  /** Hex SHA-256 of the replacement token. */
  newTokenHash: string;
  /** `now + 60 s` — how long the outgoing hash keeps resolving. */
  previousTokenExpiresAt: Date;
  now: Date;
}

/**
 * Rotate the token in place: swap `token_hash`, park the old hash in the
 * grace column, stamp `rotated_at`.
 *
 * Compare-and-swap on the CURRENT hash and on the session being unrevoked, in
 * one statement. Two concurrent rotations: exactly one wins; the loser gets
 * `undefined` and its presented hash is already parked in
 * `previous_token_hash`, so its next ordinary request still resolves.
 */
export async function rotateGuestSessionToken(
  db: DatabaseOrTransaction,
  input: RotateGuestSessionInput,
): Promise<GuestSessionRow | undefined> {
  const [row] = await db
    .update(guestSessions)
    .set({
      tokenHash: input.newTokenHash,
      previousTokenHash: input.currentTokenHash,
      previousTokenExpiresAt: input.previousTokenExpiresAt,
      rotatedAt: input.now,
    })
    .where(
      and(
        eq(guestSessions.id, input.id),
        eq(guestSessions.tokenHash, input.currentTokenHash),
        isNull(guestSessions.revokedAt),
      ),
    )
    .returning();
  return row;
}

/**
 * Set `revoked_at`. Idempotent by the same CAS shape: a second revocation
 * finds no unrevoked row and returns `false`, which is the ordinary outcome
 * of a retry and not a failure.
 */
export async function revokeGuestSession(
  db: DatabaseOrTransaction,
  id: string,
  now: Date,
): Promise<boolean> {
  const updated = await db
    .update(guestSessions)
    .set({ revokedAt: now })
    .where(and(eq(guestSessions.id, id), isNull(guestSessions.revokedAt)))
    .returning({ id: guestSessions.id });
  return updated.length === 1;
}

/** Fetch by row id — the inspect surface after resolution, and tests. */
export async function findGuestSessionById(
  db: DatabaseOrTransaction,
  id: string,
): Promise<GuestSessionRow | undefined> {
  const [row] = await db.select().from(guestSessions).where(eq(guestSessions.id, id)).limit(1);
  return row;
}
