/**
 * `docs/catalog-architecture-diagrams.md`, rendered from the derived model.
 *
 * A pure function of the model: no clock, no environment, no filesystem. That
 * is what lets the gate call it and byte-compare the result against the file on
 * disk — a generator that stamped a date would differ on every run and the
 * comparison would have to be relaxed to a diff of "the interesting parts",
 * which is a check nobody can read.
 */

import type { ArchitectureModel, CardinalityEdge, TableWriter } from './model.js';
import { FIRST_EPIC_MIGRATION_IDX } from './model.js';
import { CHILD_RIGHT, PARENT_LEFT } from './mermaid.js';

const GENERATOR = 'packages/backend/scripts/generate-architecture-diagrams.ts';
const GATE = 'packages/backend/scripts/architecture/__tests__/catalog-architecture-diagrams.test.ts';

/** A mermaid flowchart node id: safe characters only, and reversible by prefix. */
function nodeId(prefix: string, name: string): string {
  return `${prefix}_${name.replace(/[^A-Za-z0-9_]/g, '_')}`;
}

function edgeLabel(edge: CardinalityEdge): string {
  return `${edge.columns.join(' + ')} · ${edge.onDelete}`;
}

function writerSummary(writers: readonly TableWriter[] | undefined): string {
  if (!writers || writers.length === 0) return '— *no application writer*';
  return writers
    .map((writer) => `\`${writer.directory}\` (${writer.operations.join('/')})`)
    .join('<br>');
}

export function renderDocument(model: ArchitectureModel): string {
  const population = model.population;
  const known = new Set(population.keys());
  const moduleOf = new Map<string, string>();
  for (const assignment of model.modules) {
    for (const table of assignment.tables) moduleOf.set(table, assignment.module);
  }

  const epicEdges = model.edges.filter((edge) => known.has(edge.child));
  const inboundEdges = model.edges.filter((edge) => !known.has(edge.child) && known.has(edge.parent));
  const externalParents = [
    ...new Set(epicEdges.filter((edge) => !known.has(edge.parent)).map((edge) => edge.parent)),
  ].sort();

  const noWriter = [...known].filter((table) => !model.writers.has(table)).sort();
  const multiWriter = [...model.writers].filter(([, writers]) => writers.length > 1);
  const writerDirectories = [
    ...new Set([...model.writers.values()].flatMap((writers) => writers.map((writer) => writer.directory))),
  ].sort();

  const out: string[] = [];
  const push = (...lines: string[]): void => {
    out.push(...lines);
  };

  /* ----------------------------- header ----------------------------- */

  push(
    '# Catalog architecture diagrams',
    '',
    '> **GENERATED — do not edit this file.** Every arrow below is derived: cardinality from',
    "> drizzle's own table reflection, the population from the migration SQL, the module grouping",
    '> from the gated table in [`catalog-table-ownership.md`](catalog-table-ownership.md), and write',
    '> ownership from a scan of the production source.',
    '>',
    '> Regenerate: `bun run --cwd packages/backend architecture:diagrams`',
    `> Source: \`${GENERATOR}\` · Gate: \`${GATE}\``,
    '',
    '#367 Workstream 19. The companion to',
    '[`catalog-table-ownership.md`](catalog-table-ownership.md), which answers *who owns this table*',
    'in prose; this answers *what is it attached to, how many of it are there, and who writes it* in',
    'pictures. [`catalog-glossary.md`](catalog-glossary.md) carries the curated, annotated subset a',
    'newcomer should read first — its diagram is gated against the same derivation as this one, so',
    'the two cannot disagree.',
    '',
    '## Why this file is generated rather than drawn',
    '',
    'Four separate figures in `catalog-table-ownership.md` had silently rotted before #857 removed',
    'them: a table count, a journal index, a copy of `SCHEMA_TABLE_COUNT`, and a list of migrations',
    'that contradicted its own table on the day it was written. A diagram is a worse home for a fact',
    'like that than a sentence is — **a wrong arrow reads as an architectural decision rather than as',
    'an error**, so it is argued with instead of corrected.',
    '',
    'That is not hypothetical here. When this generator was first run, its output was compared',
    'against the hand-drawn ER diagram in `catalog-glossary.md`, and **eight edges there asserted a',
    'mandatory parent for a foreign key whose column is nullable**. It was one systematic omission',
    'rather than eight mistakes — that diagram never used the optional marker at all — and the',
    'load-bearing consequence was `listings }o--|| categories`, which told every reader that a',
    'listing always has a category. `listings.category_id` has been nullable since `0000`, confirmed',
    'three ways: the drizzle reflection, the `.references()` call with no `.notNull()`, and the',
    '`"category_id" text,` in the migration with no later `ALTER`. Those edges were corrected in the',
    'same change that added this file, and that diagram is now gated against the same derivation.',
    '',
    '## What is derived, and what a foreign key cannot tell you',
    '',
    'Read the markers precisely; they are emitted from schema facts and nothing else.',
    '',
    '- **`||` on the parent side** — every column of the foreign key is `NOT NULL`, so a child row',
    '  always names a parent. Derived from column nullability.',
    '- **`|o` on the parent side** — at least one foreign-key column is nullable, so the parent is',
    '  optional. Derived from column nullability.',
    '- **`o{` on the child side** — nothing in the schema bounds how many children a parent may have.',
    '  Derived from the *absence* of a covering unique.',
    '- **`o|` on the child side** — a unique constraint covers a **subset** of the foreign-key',
    '  columns, so a parent has at most one child across this key. Derived from unique constraints',
    '  and non-partial unique indexes.',
    '',
    '**No edge ever carries `}|` or `|{` ("one or more"), and that is the honest half.** "Every',
    'parent must have at least one child" is not expressible in a foreign key, a `NOT NULL` or a',
    'unique index, so no marker here may claim it. A relationship you know to be mandatory from the',
    'parent side is a fact about application code, and it belongs in prose beside the diagram rather',
    'than in the diagram.',
    '',
    'Three further limits, stated rather than left to be discovered:',
    '',
    '- **Partial unique indexes are ignored.** A unique with a `WHERE` clause constrains only the',
    '  rows matching its predicate, so reading one as a 1:1 would claim a bound the table does not',
    '  have. Expression indexes are ignored for the same reason: a unique over `lower(name)` is not a',
    '  unique over `name`.',
    '- **A unique over a *superset* of the foreign-key columns proves nothing.**',
    '  `UNIQUE(category_id, locale, normalized_alias)` permits many aliases per category; only a',
    '  unique whose columns are all *within* the foreign key pins every one of them for a given',
    '  parent row.',
    '- **Column names are the SQL names**, resolved through drizzle\'s own `CasingCache` with the',
    '  repository\'s `DATABASE_CASING`. The schema declares `categoryId`; the DDL says `category_id`.',
    '  Re-implementing that conversion here would be a third spelling of it, free to disagree with',
    '  the two that decide the real schema.',
    '',
  );

  /* ------------------------- module dependency ------------------------- */

  const moduleNames = model.modules.map((assignment) => assignment.module);
  const crossModule = new Map<string, Set<string>>();
  const toExternal = new Map<string, Set<string>>();
  for (const edge of epicEdges) {
    const from = moduleOf.get(edge.child);
    if (from === undefined) continue;
    if (known.has(edge.parent)) {
      const to = moduleOf.get(edge.parent);
      if (to === undefined || to === from) continue;
      const bucket = crossModule.get(from) ?? new Set<string>();
      bucket.add(to);
      crossModule.set(from, bucket);
    } else {
      const bucket = toExternal.get(from) ?? new Set<string>();
      bucket.add(edge.parent);
      toExternal.set(from, bucket);
    }
  }

  push(
    '## 1. Module dependency graph',
    '',
    `Each arrow is at least one foreign key from a table the module owns to a table the target owns.`,
    'Modules are the rows of the gated table in `catalog-table-ownership.md`; the right-hand column',
    'holds the pre-existing catalogue and commerce tables the epic attaches to and does not own.',
    '',
    '```mermaid',
    'flowchart LR',
  );
  push('    subgraph epic["#367 catalog modules"]', '        direction TB');
  for (const name of moduleNames) {
    push(`        ${nodeId('M', name)}["${name}"]`);
  }
  push('    end');
  push('    subgraph outside["Pre-existing tables the epic attaches to"]', '        direction TB');
  for (const table of externalParents) {
    push(`        ${nodeId('X', table)}[("${table}")]`);
  }
  push('    end');
  for (const name of moduleNames) {
    for (const target of [...(crossModule.get(name) ?? [])].sort()) {
      push(`    ${nodeId('M', name)} --> ${nodeId('M', target)}`);
    }
  }
  for (const name of moduleNames) {
    for (const target of [...(toExternal.get(name) ?? [])].sort()) {
      push(`    ${nodeId('M', name)} --> ${nodeId('X', target)}`);
    }
  }
  push('```', '');

  push(
    `**${inboundEdges.length} foreign keys point the other way** — from a table outside the epic into`,
    'one the epic added. They are the edges that make an epic table impossible to drop quietly:',
    '',
  );
  for (const edge of inboundEdges) {
    push(
      `- \`${edge.child}.${edge.columns.join(' + ')}\` → \`${edge.parent}\` (\`ON DELETE ${edge.onDelete}\`)`,
    );
  }
  push('');

  /* --------------------------- write ownership --------------------------- */

  push(
    '## 2. Write ownership',
    '',
    'Measured, not asserted. Every edge below is a `.insert(…)`, `.update(…)` or `.delete(…)` against',
    "the table's drizzle symbol, or a raw-SQL write naming it, found in a non-test module under",
    '`packages/backend/src`. The node on the left is the **directory** the writing module sits in.',
    '',
    `**${model.modules.length} modules**, **${writerDirectories.length} writing directories**,`,
    `**${multiWriter.length} tables written from more than one directory** and`,
    `**${noWriter.length} written by no application code at all**. The exceptions are drawn by name,`,
    'because they are the whole reason to look at this graph: `catalog-table-ownership.md` opens with',
    '"one module owns a table", and these are the places where more than one directory issues the',
    'statements.',
    '',
    '```mermaid',
    'flowchart LR',
  );
  for (const directory of writerDirectories) {
    push(`    ${nodeId('W', directory)}["${directory}"]`);
  }
  for (const name of moduleNames) {
    push(`    ${nodeId('M', name)}(["${name}"])`);
  }
  const directoryToModule = new Map<string, Map<string, number>>();
  for (const [table, writers] of model.writers) {
    const owner = moduleOf.get(table);
    if (owner === undefined) continue;
    for (const writer of writers) {
      const bucket = directoryToModule.get(writer.directory) ?? new Map<string, number>();
      bucket.set(owner, (bucket.get(owner) ?? 0) + 1);
      directoryToModule.set(writer.directory, bucket);
    }
  }
  for (const directory of writerDirectories) {
    for (const [owner, count] of [...(directoryToModule.get(directory) ?? [])].sort(([a], [b]) =>
      a.localeCompare(b),
    )) {
      push(`    ${nodeId('W', directory)} -->|"${count}"| ${nodeId('M', owner)}`);
    }
  }
  if (multiWriter.length > 0) {
    push('    subgraph shared["Written from more than one directory"]', '        direction TB');
    for (const [table] of multiWriter) push(`        ${nodeId('T', table)}[("${table}")]`);
    push('    end');
    for (const [table, writers] of multiWriter) {
      for (const writer of writers) {
        push(`    ${nodeId('W', writer.directory)} -.-> ${nodeId('T', table)}`);
      }
    }
  }
  if (noWriter.length > 0) {
    push('    subgraph unwritten["No application writer"]', '        direction TB');
    for (const table of noWriter) push(`        ${nodeId('T', table)}[("${table}")]`);
    push('    end');
  }
  push('```', '');

  push(
    '### Tables written from more than one directory',
    '',
    'Each of these is a real production call site, not a scanning artefact — the gate binds every',
    'entry to a file it actually read.',
    '',
    '| Table | Owning module | Writing directories |',
    '|---|---|---|',
  );
  for (const [table, writers] of multiWriter) {
    push(
      `| \`${table}\` | ${moduleOf.get(table) ?? '—'} | ${writers
        .map((writer) => `\`${writer.files.join('`, `')}\` (${writer.operations.join('/')})`)
        .join('<br>')} |`,
    );
  }
  push('');

  push(
    '### Tables no application code writes',
    '',
    'Not a gap in the map — a fact about it. A table nothing writes is the one most likely to',
    'acquire a writer nobody argues about, so it is named here rather than left as an absence.',
    '',
    '| Table | Owning module | Written by |',
    '|---|---|---|',
  );
  for (const table of noWriter) {
    push(`| \`${table}\` | ${moduleOf.get(table) ?? '—'} | a database trigger, or nothing yet |`);
  }
  push(
    '',
    '**What this scan cannot see**, stated so an empty result is never read as proof of absence: a',
    'write assembled from a table name held in a variable, a write through an aliased import (the',
    'gate fails the build if one appears), and any statement issued from outside',
    '`packages/backend/src`. `catalog-table-ownership.md` §"Who may write, per subject" carries the',
    'HTTP-reachability half, which no source scan can answer.',
    '',
  );

  /* ---------------------------- cardinality ---------------------------- */

  push(
    '## 3. Cardinality, by module',
    '',
    `All ${population.size} tables created by a migration at or after \`${String(FIRST_EPIC_MIGRATION_IDX).padStart(4, '0')}\``,
    'appear below exactly once, each under the module that owns it. Every relationship is a foreign',
    'key drizzle will emit; the label is the child columns and the `ON DELETE` action.',
    '',
  );

  for (const assignment of model.modules) {
    const owned = new Set(assignment.tables);
    const edges = epicEdges.filter((edge) => owned.has(edge.child));
    const referenced = [...new Set(edges.map((edge) => edge.parent))].filter((table) => !owned.has(table));
    push(`### ${assignment.module}`, '');
    push('```mermaid', 'erDiagram');
    for (const table of assignment.tables) {
      // Declared explicitly so a table with no foreign key at all still appears
      // as a node. Governance owns five tables and two edges; without this,
      // three of them would be silently absent from a diagram that claims to
      // carry the whole population.
      push(`    ${table} {`, '    }');
    }
    for (const edge of edges) {
      push(
        `    ${edge.parent} ${PARENT_LEFT[edge.parentSide]}--${CHILD_RIGHT[edge.childSide]} ${edge.child} : "${edgeLabel(edge)}"`,
      );
    }
    push('```', '');
    if (referenced.length > 0) {
      const inside = referenced.filter((table) => known.has(table)).sort();
      const outside = referenced.filter((table) => !known.has(table)).sort();
      if (inside.length > 0) {
        push(`Also names, from other #367 modules: ${inside.map((table) => `\`${table}\``).join(', ')}.`, '');
      }
      if (outside.length > 0) {
        push(`Also names, from outside the epic: ${outside.map((table) => `\`${table}\``).join(', ')}.`, '');
      }
    }
    push('| Table | Created by | Written by |', '|---|---|---|');
    for (const table of assignment.tables) {
      const idx = population.get(table);
      push(
        `| \`${table}\` | \`${idx === undefined ? '—' : String(idx).padStart(4, '0')}\` | ${writerSummary(model.writers.get(table))} |`,
      );
    }
    push('');
  }

  /* ------------------------------ appendix ------------------------------ */

  const oneToOne = epicEdges.filter((edge) => edge.childSide === 'atMostOne');
  const optionalParents = epicEdges.filter((edge) => edge.parentSide === 'zeroOrOne');
  const byDelete = new Map<string, number>();
  for (const edge of epicEdges) byDelete.set(edge.onDelete, (byDelete.get(edge.onDelete) ?? 0) + 1);

  push(
    '## 4. What the derivation found',
    '',
    'Counts, so that a diagram that quietly stopped measuring anything is visible as a number that',
    'moved. Every one of these is re-derived on each run and floored by the gate.',
    '',
    '| Fact | Value |',
    '|---|---|',
    `| Tables in the population | ${population.size} |`,
    `| Modules they are grouped into | ${model.modules.length} |`,
    `| Foreign keys out of an epic table | ${epicEdges.length} |`,
    `| Foreign keys into one, from outside the epic | ${inboundEdges.length} |`,
    `| Pre-existing tables the epic attaches to | ${externalParents.length} |`,
    `| Relationships the schema proves are 1:1 | ${oneToOne.length} |`,
    `| Relationships whose parent is optional (nullable FK) | ${optionalParents.length} |`,
    `| Directories that write an epic table | ${writerDirectories.length} |`,
    `| Tables written from more than one directory | ${multiWriter.length} |`,
    `| Tables no application code writes | ${noWriter.length} |`,
    '',
    `\`ON DELETE\` across those ${epicEdges.length} foreign keys: ` +
      [...byDelete]
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([action, count]) => `**${count}** \`${action}\``)
        .join(', ') +
      '.',
    '',
    '### The relationships the schema proves are 1:1',
    '',
  );
  if (oneToOne.length === 0) {
    push('None.', '');
  } else {
    for (const edge of oneToOne) {
      push(
        `- \`${edge.parent}\` → \`${edge.child}\` on \`${edge.columns.join(' + ')}\`, because a unique` +
          ' constraint covers those columns.',
      );
    }
    push('');
  }

  return `${out.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd()}\n`;
}
