import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const root = process.cwd();
const expected = JSON.parse(readFileSync(root + '/docs/audits/2026-10-04-cohort-canonical-store-ids/cohort.production.json', 'utf8'));
let attempts = 0;
globalThis.fetch = () => { attempts++; throw new Error('No remote requests permitted'); };
const { config } = await import('../../../packages/backend/src/config/index.js');
const { billingCohortSchema } = await import('../../../packages/backend/src/services/billing/peable/adapter.js');
const { getStripeClient } = await import('../../../packages/backend/src/services/payments/stripe/client.js');
assert.deepEqual(billingCohortSchema.parse(JSON.parse(config.merchantBilling.peableCohortJson)), expected);
assert.equal(config.payments.stripe.enabled, false);
assert.equal(config.payments.stripe.livemode, true);
assert.equal(config.merchantBilling.enabled, false);
assert.equal(config.payments.peable.publicKey, 'fixture-public');
assert.equal(config.payments.peable.secret, 'fixture-secret');
assert.equal(config.payments.peable.baseUrl, 'https://api.peable.to');
assert.equal(config.payments.peable.oxyApiUrl, 'https://api.oxy.so');
assert.throws(() => getStripeClient(), /STRIPE_ENABLED is off/);
assert.equal(attempts, 0);
console.log(JSON.stringify({kind:'mercaria-compiled-production-cohort-config-smoke-v1', passed:true, nodeEnv:process.env.NODE_ENV, storeIds:expected.storeIds, namespace:expected, syntheticCredentialPair:true, generalStripeEnabled:false, newBillingActionsEnabled:false, remoteFetchAttempts:attempts}));
