-- oxy:deploy-phase=pre
--
-- #122: live supplier stock, shipping, quote and reservation preflight. EIGHT
-- new tables and NOTHING else — no column is added to, dropped from or narrowed
-- on any existing table, so this migration is correct against BOTH the image
-- still serving (which never writes any of these rows) and the one arriving.
--
-- The hand-written block at the END of this file is not generated by
-- drizzle-kit and MUST be re-applied after any regeneration. It carries five
-- enforcement functions, and each holds a rule the CHECK constraints above
-- cannot express because it is about a TRANSITION rather than a row:
--
--   * `mercaria_supplier_sourcing_policy_immutable` — a published policy
--     version freezes; publishing a new version is how the policy changes
--     (the `fee_schedules` / `retail_pricing_policies` mechanism).
--   * `mercaria_supplier_quote_immutable` — a quote's identity, request and
--     ANSWER columns never change, and its usage timestamps each move NULL → a
--     value exactly once. A quote is a record of what a supplier said; an
--     editable one could authorize a sale the supplier never agreed to.
--   * `mercaria_supplier_reservation_immutable` — the same, plus the two
--     one-way usage transitions and the bounded release-retry counters. What it
--     refuses above all is a change to `provider_reservation_id`,
--     `provider_expires_at` or `declared_capabilities`: those three are what
--     make a reservation row evidence of a SUPPLIER's commitment rather than a
--     local claim.
--   * `mercaria_supplier_quote_shipping_option_append_only` and
--     `mercaria_supplier_sourcing_attempt_append_only` — UPDATE and DELETE
--     refused outright. The option set is part of the frozen answer, and an
--     attempt trail somebody can edit answers no question worth asking.
--
-- On a regeneration: `bun run db:generate` emits the CREATE TABLE statements
-- only; paste this header back at the top and the trigger block back at the
-- bottom, then grep for each of the five function names to confirm all five
-- survived, and confirm the file carries exactly ONE deploy-phase marker
-- line (the anchored form at the very top; grep with a leading `^`).

CREATE TABLE "supplier_call_leases" (
	"id" text PRIMARY KEY NOT NULL,
	"supplier_account_id" text NOT NULL,
	"slot" integer NOT NULL,
	"lease_owner" text,
	"lease_until" timestamp with time zone,
	"window_start" timestamp with time zone NOT NULL,
	"calls_in_window" integer DEFAULT 0 NOT NULL,
	"window_allowance" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT date_trunc('milliseconds', now()) NOT NULL,
	"updated_at" timestamp with time zone DEFAULT date_trunc('milliseconds', now()) NOT NULL,
	CONSTRAINT "supplier_call_leases_slot_check" CHECK ("supplier_call_leases"."slot" >= 0),
	CONSTRAINT "supplier_call_leases_lease_shape_check" CHECK (num_nonnulls("supplier_call_leases"."lease_owner", "supplier_call_leases"."lease_until") in (0, 2)),
	CONSTRAINT "supplier_call_leases_window_check" CHECK ("supplier_call_leases"."calls_in_window" >= 0 and "supplier_call_leases"."window_allowance" >= 1
          and "supplier_call_leases"."calls_in_window" <= "supplier_call_leases"."window_allowance")
);
--> statement-breakpoint
CREATE TABLE "supplier_preflight_health" (
	"id" text PRIMARY KEY NOT NULL,
	"supplier_account_id" text NOT NULL,
	"window_start" timestamp with time zone NOT NULL,
	"attempts" bigint DEFAULT 0 NOT NULL,
	"successes" bigint DEFAULT 0 NOT NULL,
	"failures" bigint DEFAULT 0 NOT NULL,
	"timeouts" bigint DEFAULT 0 NOT NULL,
	"rate_limited" bigint DEFAULT 0 NOT NULL,
	"latency_ms_total" bigint DEFAULT 0 NOT NULL,
	"latency_samples" bigint DEFAULT 0 NOT NULL,
	"consecutive_failures" integer DEFAULT 0 NOT NULL,
	"last_success_at" timestamp with time zone,
	"last_failure_at" timestamp with time zone,
	"last_failure_kind" text,
	"created_at" timestamp with time zone DEFAULT date_trunc('milliseconds', now()) NOT NULL,
	"updated_at" timestamp with time zone DEFAULT date_trunc('milliseconds', now()) NOT NULL,
	CONSTRAINT "supplier_preflight_health_last_failure_kind_check" CHECK ("supplier_preflight_health"."last_failure_kind" in ('timeout', 'rate_limited', 'provider_error', 'transport_error', 'contract_violation', 'authentication_failed', 'capability_missing')),
	CONSTRAINT "supplier_preflight_health_counters_total_check" CHECK ("supplier_preflight_health"."attempts" = "supplier_preflight_health"."successes" + "supplier_preflight_health"."failures"),
	CONSTRAINT "supplier_preflight_health_counters_bounds_check" CHECK ("supplier_preflight_health"."successes" >= 0 and "supplier_preflight_health"."failures" >= 0
          and "supplier_preflight_health"."timeouts" between 0 and "supplier_preflight_health"."failures"
          and "supplier_preflight_health"."rate_limited" between 0 and "supplier_preflight_health"."failures"
          and "supplier_preflight_health"."latency_ms_total" >= 0
          and "supplier_preflight_health"."latency_samples" between 0 and "supplier_preflight_health"."attempts"
          and "supplier_preflight_health"."consecutive_failures" >= 0),
	CONSTRAINT "supplier_preflight_health_failure_shape_check" CHECK (num_nonnulls("supplier_preflight_health"."last_failure_at", "supplier_preflight_health"."last_failure_kind") in (0, 2))
);
--> statement-breakpoint
CREATE TABLE "supplier_preflight_suppressions" (
	"id" text PRIMARY KEY NOT NULL,
	"scope" text NOT NULL,
	"supplier_id" text,
	"supplier_account_id" text,
	"market_country" text,
	"kind" text NOT NULL,
	"origin" text NOT NULL,
	"reason" text NOT NULL,
	"sourcing_policy_id" text,
	"raised_by_oxy_user_id" text,
	"effective_from" timestamp with time zone NOT NULL,
	"expires_at" timestamp with time zone,
	"lifted_at" timestamp with time zone,
	"lifted_by_oxy_user_id" text,
	"lift_reason" text,
	"created_at" timestamp with time zone DEFAULT date_trunc('milliseconds', now()) NOT NULL,
	"updated_at" timestamp with time zone DEFAULT date_trunc('milliseconds', now()) NOT NULL,
	"suppression_key" text GENERATED ALWAYS AS ("scope" || '|' || coalesce("supplier_id", '') || '|' ||
            coalesce("supplier_account_id", '') || '|' || coalesce("market_country", '') || '|' || "kind") STORED NOT NULL,
	CONSTRAINT "supplier_preflight_suppressions_scope_check" CHECK ("supplier_preflight_suppressions"."scope" in ('supplier', 'supplier_account', 'market', 'supplier_account_market')),
	CONSTRAINT "supplier_preflight_suppressions_kind_check" CHECK ("supplier_preflight_suppressions"."kind" in ('kill_switch', 'health_degraded', 'quota_exhausted', 'capability_unavailable')),
	CONSTRAINT "supplier_preflight_suppressions_origin_check" CHECK ("supplier_preflight_suppressions"."origin" in ('operator', 'automatic_health')),
	CONSTRAINT "supplier_preflight_suppressions_scope_shape_check" CHECK (case "supplier_preflight_suppressions"."scope"
            when 'supplier' then "supplier_preflight_suppressions"."supplier_id" is not null
                                 and "supplier_preflight_suppressions"."supplier_account_id" is null
                                 and "supplier_preflight_suppressions"."market_country" is null
            when 'supplier_account' then "supplier_preflight_suppressions"."supplier_account_id" is not null
                                 and "supplier_preflight_suppressions"."supplier_id" is null
                                 and "supplier_preflight_suppressions"."market_country" is null
            when 'market' then "supplier_preflight_suppressions"."market_country" is not null
                                 and "supplier_preflight_suppressions"."supplier_id" is null
                                 and "supplier_preflight_suppressions"."supplier_account_id" is null
            when 'supplier_account_market' then "supplier_preflight_suppressions"."supplier_account_id" is not null
                                 and "supplier_preflight_suppressions"."market_country" is not null
                                 and "supplier_preflight_suppressions"."supplier_id" is null
            else false
          end),
	CONSTRAINT "supplier_preflight_suppressions_market_shape_check" CHECK ("supplier_preflight_suppressions"."market_country" is null or "supplier_preflight_suppressions"."market_country" ~ '^[A-Z]{2}$'),
	CONSTRAINT "supplier_preflight_suppressions_reason_check" CHECK (length(btrim("supplier_preflight_suppressions"."reason")) between 1 and 2000),
	CONSTRAINT "supplier_preflight_suppressions_origin_shape_check" CHECK (case "supplier_preflight_suppressions"."origin"
            when 'automatic_health' then "supplier_preflight_suppressions"."kind" = 'health_degraded'
                                       and "supplier_preflight_suppressions"."raised_by_oxy_user_id" is null
                                       and "supplier_preflight_suppressions"."sourcing_policy_id" is not null
                                       and "supplier_preflight_suppressions"."expires_at" is not null
            else "supplier_preflight_suppressions"."raised_by_oxy_user_id" is not null
          end),
	CONSTRAINT "supplier_preflight_suppressions_window_check" CHECK ("supplier_preflight_suppressions"."expires_at" is null or "supplier_preflight_suppressions"."expires_at" > "supplier_preflight_suppressions"."effective_from"),
	CONSTRAINT "supplier_preflight_suppressions_lift_check" CHECK (num_nonnulls("supplier_preflight_suppressions"."lifted_at", "supplier_preflight_suppressions"."lift_reason") in (0, 2)
          and ("supplier_preflight_suppressions"."lifted_by_oxy_user_id" is null or "supplier_preflight_suppressions"."lifted_at" is not null)
          and ("supplier_preflight_suppressions"."lift_reason" is null
               or length(btrim("supplier_preflight_suppressions"."lift_reason")) <= 2000))
);
--> statement-breakpoint
CREATE TABLE "supplier_quote_shipping_options" (
	"id" text PRIMARY KEY NOT NULL,
	"quote_id" text NOT NULL,
	"service_code" text NOT NULL,
	"carrier" text,
	"service_name" text,
	"cost_amount" bigint NOT NULL,
	"cost_currency" text NOT NULL,
	"basis" text NOT NULL,
	"delivery_days_min" integer,
	"delivery_days_max" integer,
	"guaranteed" boolean DEFAULT false NOT NULL,
	"position" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT date_trunc('milliseconds', now()) NOT NULL,
	CONSTRAINT "supplier_quote_shipping_options_basis_check" CHECK ("supplier_quote_shipping_options"."basis" in ('basket', 'per_item', 'unknown')),
	CONSTRAINT "supplier_quote_shipping_options_cost_currency_check" CHECK ("supplier_quote_shipping_options"."cost_currency" in ('FAIR', 'USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY', 'CHF', 'CNY', 'SEK', 'NOK', 'DKK', 'PLN', 'MXN', 'BRL', 'INR', 'NZD', 'ZAR', 'SGD', 'HKD', 'AED')),
	CONSTRAINT "supplier_quote_shipping_options_service_code_check" CHECK (length(btrim("supplier_quote_shipping_options"."service_code")) > 0),
	CONSTRAINT "supplier_quote_shipping_options_cost_check" CHECK ("supplier_quote_shipping_options"."cost_amount" >= 0),
	CONSTRAINT "supplier_quote_shipping_options_known_basis_check" CHECK ("supplier_quote_shipping_options"."basis" <> 'unknown'),
	CONSTRAINT "supplier_quote_shipping_options_window_check" CHECK (num_nonnulls("supplier_quote_shipping_options"."delivery_days_min", "supplier_quote_shipping_options"."delivery_days_max") in (0, 2)
          and ("supplier_quote_shipping_options"."delivery_days_min" is null
               or ("supplier_quote_shipping_options"."delivery_days_min" >= 0 and "supplier_quote_shipping_options"."delivery_days_max" >= "supplier_quote_shipping_options"."delivery_days_min")))
);
--> statement-breakpoint
CREATE TABLE "supplier_quotes" (
	"id" text PRIMARY KEY NOT NULL,
	"idempotency_key" text NOT NULL,
	"request_fingerprint" text NOT NULL,
	"supplier_id" text NOT NULL,
	"supplier_account_id" text NOT NULL,
	"environment" text NOT NULL,
	"provider" text NOT NULL,
	"declared_capabilities" text[] DEFAULT '{}' NOT NULL,
	"procurement_offer_id" text,
	"canonical_product_id" text,
	"canonical_variant_id" text,
	"supplier_sku" text NOT NULL,
	"quantity" integer NOT NULL,
	"checkout_group_id" text,
	"order_id" text,
	"requested_currency" text NOT NULL,
	"destination_country" text NOT NULL,
	"destination_region" text,
	"identity_confirmation" text NOT NULL,
	"availability" text NOT NULL,
	"max_orderable_quantity" integer,
	"minimum_order_quantity" integer,
	"pack_size" integer,
	"unit_cost_amount" bigint,
	"unit_cost_currency" text,
	"supplier_fees_amount" bigint,
	"supplier_fees_currency" text,
	"shipping_cost_amount" bigint,
	"shipping_cost_currency" text,
	"shipping_basis" text NOT NULL,
	"selected_shipping_service_code" text,
	"handling_days_min" integer,
	"handling_days_max" integer,
	"dispatch_days_min" integer,
	"dispatch_days_max" integer,
	"delivery_days_min" integer,
	"delivery_days_max" integer,
	"tax_amount" bigint,
	"tax_currency" text,
	"duty_amount" bigint,
	"duty_currency" text,
	"import_responsibility" text,
	"fulfilment_origin_country" text,
	"destination_restrictions" text[] DEFAULT '{}' NOT NULL,
	"provider_quote_reference" text,
	"price_guarantee" text NOT NULL,
	"stock_guarantee" text NOT NULL,
	"provider_reason_codes" text[] DEFAULT '{}' NOT NULL,
	"source_record_ref" text,
	"status" text NOT NULL,
	"block_reasons" text[] DEFAULT '{}' NOT NULL,
	"exception_kind" text,
	"sourcing_policy_id" text,
	"sourcing_policy_key" text,
	"sourcing_policy_version" integer,
	"pricing_policy_key" text,
	"pricing_policy_version" integer,
	"eligibility_policy_key" text,
	"eligibility_policy_version" integer,
	"requested_at" timestamp with time zone NOT NULL,
	"quoted_at" timestamp with time zone NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"consumed_at" timestamp with time zone,
	"consumed_by_checkout_group_id" text,
	"released_at" timestamp with time zone,
	"release_reason" text,
	"superseded_by_quote_id" text,
	"supersede_reason" text,
	"attempts" integer DEFAULT 1 NOT NULL,
	"last_failure_kind" text,
	"last_failure_at" timestamp with time zone,
	"last_failure_message" text,
	"latency_ms" integer,
	"created_at" timestamp with time zone DEFAULT date_trunc('milliseconds', now()) NOT NULL,
	"updated_at" timestamp with time zone DEFAULT date_trunc('milliseconds', now()) NOT NULL,
	CONSTRAINT "supplier_quotes_environment_check" CHECK ("supplier_quotes"."environment" in ('test', 'live')),
	CONSTRAINT "supplier_quotes_identity_check" CHECK ("supplier_quotes"."identity_confirmation" in ('confirmed', 'mismatched', 'ambiguous', 'unknown')),
	CONSTRAINT "supplier_quotes_availability_check" CHECK ("supplier_quotes"."availability" in ('orderable', 'unavailable', 'restricted', 'backordered', 'unknown')),
	CONSTRAINT "supplier_quotes_shipping_basis_check" CHECK ("supplier_quotes"."shipping_basis" in ('basket', 'per_item', 'unknown')),
	CONSTRAINT "supplier_quotes_import_responsibility_check" CHECK ("supplier_quotes"."import_responsibility" in ('supplier', 'mercaria', 'customer', 'unknown')),
	CONSTRAINT "supplier_quotes_price_guarantee_check" CHECK ("supplier_quotes"."price_guarantee" in ('guaranteed', 'advisory')),
	CONSTRAINT "supplier_quotes_stock_guarantee_check" CHECK ("supplier_quotes"."stock_guarantee" in ('guaranteed', 'advisory')),
	CONSTRAINT "supplier_quotes_status_check" CHECK ("supplier_quotes"."status" in ('complete', 'partial', 'invalid')),
	CONSTRAINT "supplier_quotes_exception_kind_check" CHECK ("supplier_quotes"."exception_kind" in ('ambiguous_sku_identity', 'ambiguous_availability', 'currency_mismatch', 'conflicting_shipping_basis', 'quantity_contract_violation', 'provider_contract_violation')),
	CONSTRAINT "supplier_quotes_release_reason_check" CHECK ("supplier_quotes"."release_reason" in ('checkout_abandoned', 'checkout_failed', 'quote_superseded', 'expired', 'operator_release', 'sourcing_failover')),
	CONSTRAINT "supplier_quotes_supersede_reason_check" CHECK ("supplier_quotes"."supersede_reason" in ('re_preflight', 'cost_changed', 'stock_changed', 'destination_changed', 'quantity_changed', 'quote_expired', 'sourcing_failover')),
	CONSTRAINT "supplier_quotes_last_failure_kind_check" CHECK ("supplier_quotes"."last_failure_kind" in ('timeout', 'rate_limited', 'provider_error', 'transport_error', 'contract_violation', 'authentication_failed', 'capability_missing')),
	CONSTRAINT "supplier_quotes_declared_capabilities_check" CHECK ("supplier_quotes"."declared_capabilities" <@ array['live_product_lookup', 'live_stock_lookup', 'destination_shipping_quote', 'order_draft_validation', 'inventory_reservation', 'quote_expiry', 'price_guarantee', 'address_validation', 'delivery_estimate', 'tax_duty_estimate', 'cancellation_before_submission', 'update_notifications']::text[]),
	CONSTRAINT "supplier_quotes_destination_restrictions_check" CHECK ("supplier_quotes"."destination_restrictions" <@ array['not_served', 'postal_code_excluded', 'hazardous_goods_restricted', 'oversize_restricted', 'customs_documentation_required', 'age_restricted', 'carrier_unavailable', 'import_licence_required']::text[]),
	CONSTRAINT "supplier_quotes_provider_reason_codes_check" CHECK ("supplier_quotes"."provider_reason_codes" <@ array['out_of_stock', 'discontinued', 'sku_unknown', 'sku_ambiguous', 'quantity_exceeds_stock', 'destination_unsupported', 'service_unavailable', 'currency_unsupported', 'account_suspended', 'credential_invalid', 'rate_limited', 'provider_internal_error', 'validation_rejected', 'other']::text[]),
	CONSTRAINT "supplier_quotes_block_reasons_check" CHECK ("supplier_quotes"."block_reasons" <@ array['availability_unknown', 'not_orderable', 'identity_unconfirmed', 'identity_mismatched', 'identity_ambiguous', 'unit_cost_unknown', 'shipping_cost_unknown', 'shipping_service_unavailable', 'delivery_estimate_unknown', 'tax_treatment_unknown', 'quantity_above_maximum', 'quantity_below_minimum', 'pack_size_violated', 'destination_restricted', 'currency_unsupported', 'capability_missing', 'provider_timeout', 'provider_rate_limited', 'provider_error', 'provider_unconfigured', 'preflight_disabled', 'supplier_suppressed', 'market_suppressed', 'account_not_active', 'offer_ineligible', 'sourcing_policy_missing', 'provider_contract_violation']::text[]),
	CONSTRAINT "supplier_quotes_requested_currency_check" CHECK ("supplier_quotes"."requested_currency" in ('FAIR', 'USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY', 'CHF', 'CNY', 'SEK', 'NOK', 'DKK', 'PLN', 'MXN', 'BRL', 'INR', 'NZD', 'ZAR', 'SGD', 'HKD', 'AED')),
	CONSTRAINT "supplier_quotes_unit_cost_currency_check" CHECK ("supplier_quotes"."unit_cost_currency" in ('FAIR', 'USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY', 'CHF', 'CNY', 'SEK', 'NOK', 'DKK', 'PLN', 'MXN', 'BRL', 'INR', 'NZD', 'ZAR', 'SGD', 'HKD', 'AED')),
	CONSTRAINT "supplier_quotes_supplier_fees_currency_check" CHECK ("supplier_quotes"."supplier_fees_currency" in ('FAIR', 'USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY', 'CHF', 'CNY', 'SEK', 'NOK', 'DKK', 'PLN', 'MXN', 'BRL', 'INR', 'NZD', 'ZAR', 'SGD', 'HKD', 'AED')),
	CONSTRAINT "supplier_quotes_shipping_cost_currency_check" CHECK ("supplier_quotes"."shipping_cost_currency" in ('FAIR', 'USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY', 'CHF', 'CNY', 'SEK', 'NOK', 'DKK', 'PLN', 'MXN', 'BRL', 'INR', 'NZD', 'ZAR', 'SGD', 'HKD', 'AED')),
	CONSTRAINT "supplier_quotes_tax_currency_check" CHECK ("supplier_quotes"."tax_currency" in ('FAIR', 'USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY', 'CHF', 'CNY', 'SEK', 'NOK', 'DKK', 'PLN', 'MXN', 'BRL', 'INR', 'NZD', 'ZAR', 'SGD', 'HKD', 'AED')),
	CONSTRAINT "supplier_quotes_duty_currency_check" CHECK ("supplier_quotes"."duty_currency" in ('FAIR', 'USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY', 'CHF', 'CNY', 'SEK', 'NOK', 'DKK', 'PLN', 'MXN', 'BRL', 'INR', 'NZD', 'ZAR', 'SGD', 'HKD', 'AED')),
	CONSTRAINT "supplier_quotes_idempotency_key_check" CHECK (length(btrim("supplier_quotes"."idempotency_key")) > 0),
	CONSTRAINT "supplier_quotes_fingerprint_check" CHECK ("supplier_quotes"."request_fingerprint" ~ '^[a-f0-9]{64}$'),
	CONSTRAINT "supplier_quotes_provider_check" CHECK ("supplier_quotes"."provider" ~ '^[a-z0-9][a-z0-9_-]*$'),
	CONSTRAINT "supplier_quotes_supplier_sku_check" CHECK (length("supplier_quotes"."supplier_sku") > 0),
	CONSTRAINT "supplier_quotes_quantity_check" CHECK ("supplier_quotes"."quantity" > 0),
	CONSTRAINT "supplier_quotes_destination_shape_check" CHECK ("supplier_quotes"."destination_country" ~ '^[A-Z]{2}$'
          and ("supplier_quotes"."fulfilment_origin_country" is null or "supplier_quotes"."fulfilment_origin_country" ~ '^[A-Z]{2}$')),
	CONSTRAINT "supplier_quotes_money_completeness_check" CHECK (num_nonnulls("supplier_quotes"."unit_cost_amount", "supplier_quotes"."unit_cost_currency") in (0, 2)
          and num_nonnulls("supplier_quotes"."supplier_fees_amount", "supplier_quotes"."supplier_fees_currency") in (0, 2)
          and num_nonnulls("supplier_quotes"."shipping_cost_amount", "supplier_quotes"."shipping_cost_currency") in (0, 2)
          and num_nonnulls("supplier_quotes"."tax_amount", "supplier_quotes"."tax_currency") in (0, 2)
          and num_nonnulls("supplier_quotes"."duty_amount", "supplier_quotes"."duty_currency") in (0, 2)),
	CONSTRAINT "supplier_quotes_money_amounts_check" CHECK (coalesce("supplier_quotes"."unit_cost_amount", 0) >= 0
          and coalesce("supplier_quotes"."supplier_fees_amount", 0) >= 0
          and coalesce("supplier_quotes"."shipping_cost_amount", 0) >= 0
          and coalesce("supplier_quotes"."tax_amount", 0) >= 0
          and coalesce("supplier_quotes"."duty_amount", 0) >= 0),
	CONSTRAINT "supplier_quotes_currency_coherence_check" CHECK (coalesce("supplier_quotes"."unit_cost_currency", "supplier_quotes"."requested_currency") = "supplier_quotes"."requested_currency"
          and coalesce("supplier_quotes"."supplier_fees_currency", "supplier_quotes"."requested_currency") = "supplier_quotes"."requested_currency"
          and coalesce("supplier_quotes"."shipping_cost_currency", "supplier_quotes"."requested_currency") = "supplier_quotes"."requested_currency"
          and coalesce("supplier_quotes"."tax_currency", "supplier_quotes"."requested_currency") = "supplier_quotes"."requested_currency"
          and coalesce("supplier_quotes"."duty_currency", "supplier_quotes"."requested_currency") = "supplier_quotes"."requested_currency"),
	CONSTRAINT "supplier_quotes_windows_check" CHECK (num_nonnulls("supplier_quotes"."handling_days_min", "supplier_quotes"."handling_days_max") in (0, 2)
          and ("supplier_quotes"."handling_days_min" is null
               or ("supplier_quotes"."handling_days_min" >= 0 and "supplier_quotes"."handling_days_max" >= "supplier_quotes"."handling_days_min"))
          and num_nonnulls("supplier_quotes"."dispatch_days_min", "supplier_quotes"."dispatch_days_max") in (0, 2)
          and ("supplier_quotes"."dispatch_days_min" is null
               or ("supplier_quotes"."dispatch_days_min" >= 0 and "supplier_quotes"."dispatch_days_max" >= "supplier_quotes"."dispatch_days_min"))
          and num_nonnulls("supplier_quotes"."delivery_days_min", "supplier_quotes"."delivery_days_max") in (0, 2)
          and ("supplier_quotes"."delivery_days_min" is null
               or ("supplier_quotes"."delivery_days_min" >= 0 and "supplier_quotes"."delivery_days_max" >= "supplier_quotes"."delivery_days_min"))),
	CONSTRAINT "supplier_quotes_quantity_bounds_check" CHECK (("supplier_quotes"."max_orderable_quantity" is null or "supplier_quotes"."max_orderable_quantity" >= 0)
          and ("supplier_quotes"."minimum_order_quantity" is null or "supplier_quotes"."minimum_order_quantity" >= 1)
          and ("supplier_quotes"."pack_size" is null or "supplier_quotes"."pack_size" >= 1)),
	CONSTRAINT "supplier_quotes_complete_requirements_check" CHECK ("supplier_quotes"."status" <> 'complete'
          or ("supplier_quotes"."availability" in ('orderable')
              and "supplier_quotes"."identity_confirmation" = 'confirmed'
              and "supplier_quotes"."unit_cost_amount" is not null
              and "supplier_quotes"."shipping_cost_amount" is not null
              and "supplier_quotes"."shipping_basis" <> 'unknown'
              and "supplier_quotes"."selected_shipping_service_code" is not null
              and cardinality("supplier_quotes"."destination_restrictions") = 0)),
	CONSTRAINT "supplier_quotes_block_reason_presence_check" CHECK (("supplier_quotes"."status" = 'complete') = (cardinality("supplier_quotes"."block_reasons") = 0)),
	CONSTRAINT "supplier_quotes_exception_presence_check" CHECK (("supplier_quotes"."status" = 'invalid') = ("supplier_quotes"."exception_kind" is not null)),
	CONSTRAINT "supplier_quotes_sourcing_policy_check" CHECK (num_nonnulls("supplier_quotes"."sourcing_policy_id", "supplier_quotes"."sourcing_policy_key", "supplier_quotes"."sourcing_policy_version") in (0, 3)
          and ("supplier_quotes"."sourcing_policy_version" is null or "supplier_quotes"."sourcing_policy_version" >= 1)),
	CONSTRAINT "supplier_quotes_pricing_policy_check" CHECK (num_nonnulls("supplier_quotes"."pricing_policy_key", "supplier_quotes"."pricing_policy_version") in (0, 2)
          and num_nonnulls("supplier_quotes"."eligibility_policy_key", "supplier_quotes"."eligibility_policy_version") in (0, 2)),
	CONSTRAINT "supplier_quotes_validity_window_check" CHECK ("supplier_quotes"."expires_at" > "supplier_quotes"."quoted_at" and "supplier_quotes"."quoted_at" >= "supplier_quotes"."requested_at"),
	CONSTRAINT "supplier_quotes_consumption_check" CHECK (num_nonnulls("supplier_quotes"."consumed_at", "supplier_quotes"."consumed_by_checkout_group_id") in (0, 2)
          and ("supplier_quotes"."consumed_by_checkout_group_id" is null
               or "supplier_quotes"."checkout_group_id" is null
               or "supplier_quotes"."consumed_by_checkout_group_id" = "supplier_quotes"."checkout_group_id")),
	CONSTRAINT "supplier_quotes_release_check" CHECK (num_nonnulls("supplier_quotes"."released_at", "supplier_quotes"."release_reason") in (0, 2)),
	CONSTRAINT "supplier_quotes_usage_exclusivity_check" CHECK (num_nonnulls("supplier_quotes"."consumed_at", "supplier_quotes"."released_at") <= 1),
	CONSTRAINT "supplier_quotes_supersede_check" CHECK (num_nonnulls("supplier_quotes"."superseded_by_quote_id", "supplier_quotes"."supersede_reason") in (0, 2)
          and ("supplier_quotes"."superseded_by_quote_id" is null or "supplier_quotes"."superseded_by_quote_id" <> "supplier_quotes"."id")),
	CONSTRAINT "supplier_quotes_failure_check" CHECK ("supplier_quotes"."attempts" >= 1
          and ("supplier_quotes"."latency_ms" is null or "supplier_quotes"."latency_ms" >= 0)
          and num_nonnulls("supplier_quotes"."last_failure_kind", "supplier_quotes"."last_failure_at") in (0, 2)
          and ("supplier_quotes"."last_failure_message" is null
               or length("supplier_quotes"."last_failure_message") <= 2000))
);
--> statement-breakpoint
CREATE TABLE "supplier_reservations" (
	"id" text PRIMARY KEY NOT NULL,
	"quote_id" text NOT NULL,
	"supplier_id" text NOT NULL,
	"supplier_account_id" text NOT NULL,
	"procurement_offer_id" text,
	"provider_reservation_id" text NOT NULL,
	"declared_capabilities" text[] NOT NULL,
	"supplier_sku" text NOT NULL,
	"quantity" integer NOT NULL,
	"reserved_at" timestamp with time zone NOT NULL,
	"provider_expires_at" timestamp with time zone NOT NULL,
	"single_use" boolean DEFAULT true NOT NULL,
	"consumed_at" timestamp with time zone,
	"consumed_by_checkout_group_id" text,
	"consumed_order_id" text,
	"released_at" timestamp with time zone,
	"release_reason" text,
	"release_attempts" integer DEFAULT 0 NOT NULL,
	"last_release_error" text,
	"created_at" timestamp with time zone DEFAULT date_trunc('milliseconds', now()) NOT NULL,
	"updated_at" timestamp with time zone DEFAULT date_trunc('milliseconds', now()) NOT NULL,
	CONSTRAINT "supplier_reservations_release_reason_check" CHECK ("supplier_reservations"."release_reason" in ('checkout_abandoned', 'checkout_failed', 'quote_superseded', 'expired', 'operator_release', 'sourcing_failover')),
	CONSTRAINT "supplier_reservations_declared_capabilities_check" CHECK ("supplier_reservations"."declared_capabilities" <@ array['live_product_lookup', 'live_stock_lookup', 'destination_shipping_quote', 'order_draft_validation', 'inventory_reservation', 'quote_expiry', 'price_guarantee', 'address_validation', 'delivery_estimate', 'tax_duty_estimate', 'cancellation_before_submission', 'update_notifications']::text[]),
	CONSTRAINT "supplier_reservations_capability_declared_check" CHECK ('inventory_reservation' = any("supplier_reservations"."declared_capabilities")),
	CONSTRAINT "supplier_reservations_provider_id_check" CHECK (length(btrim("supplier_reservations"."provider_reservation_id")) > 0),
	CONSTRAINT "supplier_reservations_supplier_sku_check" CHECK (length("supplier_reservations"."supplier_sku") > 0),
	CONSTRAINT "supplier_reservations_quantity_check" CHECK ("supplier_reservations"."quantity" > 0),
	CONSTRAINT "supplier_reservations_window_check" CHECK ("supplier_reservations"."provider_expires_at" > "supplier_reservations"."reserved_at"),
	CONSTRAINT "supplier_reservations_consumption_check" CHECK (num_nonnulls("supplier_reservations"."consumed_at", "supplier_reservations"."consumed_by_checkout_group_id") in (0, 2)),
	CONSTRAINT "supplier_reservations_release_shape_check" CHECK (num_nonnulls("supplier_reservations"."released_at", "supplier_reservations"."release_reason") in (0, 2)
          and "supplier_reservations"."release_attempts" >= 0
          and ("supplier_reservations"."last_release_error" is null
               or length("supplier_reservations"."last_release_error") <= 2000)),
	CONSTRAINT "supplier_reservations_usage_exclusivity_check" CHECK (num_nonnulls("supplier_reservations"."consumed_at", "supplier_reservations"."released_at") <= 1)
);
--> statement-breakpoint
CREATE TABLE "supplier_sourcing_attempts" (
	"id" text PRIMARY KEY NOT NULL,
	"request_fingerprint" text NOT NULL,
	"sequence" integer NOT NULL,
	"checkout_group_id" text,
	"supplier_id" text NOT NULL,
	"supplier_account_id" text NOT NULL,
	"procurement_offer_id" text,
	"sourcing_policy_id" text,
	"sourcing_policy_key" text,
	"sourcing_policy_version" integer,
	"rank" integer,
	"outcome" text NOT NULL,
	"reason" text NOT NULL,
	"quote_id" text,
	"at" timestamp with time zone NOT NULL,
	CONSTRAINT "supplier_sourcing_attempts_outcome_check" CHECK ("supplier_sourcing_attempts"."outcome" in ('selected', 'skipped', 'failed', 'refused', 'superseded')),
	CONSTRAINT "supplier_sourcing_attempts_reason_check" CHECK ("supplier_sourcing_attempts"."reason" in ('selected_by_policy', 'offer_ineligible', 'supplier_suppressed', 'market_suppressed', 'account_not_active', 'capability_missing', 'concentration_limit', 'attempt_limit_reached', 'rate_limited', 'provider_timeout', 'provider_error', 'answer_incomplete', 'substitution_refused', 'terms_already_locked', 'no_active_policy', 'no_candidate')),
	CONSTRAINT "supplier_sourcing_attempts_fingerprint_check" CHECK ("supplier_sourcing_attempts"."request_fingerprint" ~ '^[a-f0-9]{64}$'),
	CONSTRAINT "supplier_sourcing_attempts_sequence_check" CHECK ("supplier_sourcing_attempts"."sequence" >= 0 and ("supplier_sourcing_attempts"."rank" is null or "supplier_sourcing_attempts"."rank" >= 0)),
	CONSTRAINT "supplier_sourcing_attempts_policy_check" CHECK (num_nonnulls("supplier_sourcing_attempts"."sourcing_policy_id", "supplier_sourcing_attempts"."sourcing_policy_key", "supplier_sourcing_attempts"."sourcing_policy_version") in (0, 3)),
	CONSTRAINT "supplier_sourcing_attempts_selected_quote_check" CHECK (("supplier_sourcing_attempts"."outcome" = 'selected') = ("supplier_sourcing_attempts"."quote_id" is not null))
);
--> statement-breakpoint
CREATE TABLE "supplier_sourcing_policies" (
	"id" text PRIMARY KEY NOT NULL,
	"policy_key" text NOT NULL,
	"version" integer NOT NULL,
	"name" text NOT NULL,
	"summary" text NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"effective_start" timestamp with time zone NOT NULL,
	"effective_end" timestamp with time zone,
	"ranking_criteria" text[] DEFAULT '{}' NOT NULL,
	"required_capabilities" text[] DEFAULT '{}' NOT NULL,
	"max_sourcing_attempts" integer DEFAULT 3 NOT NULL,
	"max_supplier_share_bps" integer DEFAULT 10000 NOT NULL,
	"quote_ttl_seconds" integer DEFAULT 900 NOT NULL,
	"provider_timeout_ms" integer DEFAULT 8000 NOT NULL,
	"max_provider_concurrency" integer DEFAULT 4 NOT NULL,
	"max_provider_calls_per_minute" integer DEFAULT 120 NOT NULL,
	"health_window_minutes" integer DEFAULT 15 NOT NULL,
	"health_minimum_samples" integer DEFAULT 20 NOT NULL,
	"health_max_failure_bps" integer DEFAULT 5000 NOT NULL,
	"health_suppression_minutes" integer DEFAULT 15 NOT NULL,
	"created_by_oxy_user_id" text NOT NULL,
	"approved_by_oxy_user_id" text,
	"activated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT date_trunc('milliseconds', now()) NOT NULL,
	"updated_at" timestamp with time zone DEFAULT date_trunc('milliseconds', now()) NOT NULL,
	CONSTRAINT "supplier_sourcing_policies_status_check" CHECK ("supplier_sourcing_policies"."status" in ('draft', 'active', 'superseded', 'retired')),
	CONSTRAINT "supplier_sourcing_policies_ranking_criteria_check" CHECK ("supplier_sourcing_policies"."ranking_criteria" <@ array['total_landed_cost', 'destination_eligibility', 'offer_freshness', 'delivery_promise', 'return_capability', 'supplier_health', 'concentration_headroom', 'reservation_capability']::text[]),
	CONSTRAINT "supplier_sourcing_policies_required_capabilities_check" CHECK ("supplier_sourcing_policies"."required_capabilities" <@ array['live_product_lookup', 'live_stock_lookup', 'destination_shipping_quote', 'order_draft_validation', 'inventory_reservation', 'quote_expiry', 'price_guarantee', 'address_validation', 'delivery_estimate', 'tax_duty_estimate', 'cancellation_before_submission', 'update_notifications']::text[]),
	CONSTRAINT "supplier_sourcing_policies_version_check" CHECK ("supplier_sourcing_policies"."version" >= 1),
	CONSTRAINT "supplier_sourcing_policies_key_check" CHECK ("supplier_sourcing_policies"."policy_key" ~ '^[a-z0-9][a-z0-9-]{1,63}$'),
	CONSTRAINT "supplier_sourcing_policies_cost_criterion_check" CHECK ('total_landed_cost' = any("supplier_sourcing_policies"."ranking_criteria")),
	CONSTRAINT "supplier_sourcing_policies_attempts_check" CHECK ("supplier_sourcing_policies"."max_sourcing_attempts" between 1 and 5),
	CONSTRAINT "supplier_sourcing_policies_share_check" CHECK ("supplier_sourcing_policies"."max_supplier_share_bps" between 1 and 10000),
	CONSTRAINT "supplier_sourcing_policies_timing_check" CHECK ("supplier_sourcing_policies"."quote_ttl_seconds" >= 1
          and "supplier_sourcing_policies"."provider_timeout_ms" between 100 and 60000
          and "supplier_sourcing_policies"."max_provider_concurrency" >= 1
          and "supplier_sourcing_policies"."max_provider_calls_per_minute" >= 1),
	CONSTRAINT "supplier_sourcing_policies_health_check" CHECK ("supplier_sourcing_policies"."health_window_minutes" >= 1
          and "supplier_sourcing_policies"."health_minimum_samples" >= 1
          and "supplier_sourcing_policies"."health_max_failure_bps" between 1 and 10000
          and "supplier_sourcing_policies"."health_suppression_minutes" >= 1),
	CONSTRAINT "supplier_sourcing_policies_effective_window_check" CHECK ("supplier_sourcing_policies"."effective_end" is null or "supplier_sourcing_policies"."effective_end" > "supplier_sourcing_policies"."effective_start"),
	CONSTRAINT "supplier_sourcing_policies_activation_audit_check" CHECK ("supplier_sourcing_policies"."status" not in ('active', 'superseded')
          or ("supplier_sourcing_policies"."approved_by_oxy_user_id" is not null and "supplier_sourcing_policies"."activated_at" is not null))
);
--> statement-breakpoint
ALTER TABLE "supplier_call_leases" ADD CONSTRAINT "supplier_call_leases_supplier_account_id_supplier_accounts_id_fk" FOREIGN KEY ("supplier_account_id") REFERENCES "public"."supplier_accounts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supplier_preflight_health" ADD CONSTRAINT "supplier_preflight_health_supplier_account_id_supplier_accounts_id_fk" FOREIGN KEY ("supplier_account_id") REFERENCES "public"."supplier_accounts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supplier_preflight_suppressions" ADD CONSTRAINT "supplier_preflight_suppressions_supplier_id_suppliers_id_fk" FOREIGN KEY ("supplier_id") REFERENCES "public"."suppliers"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supplier_preflight_suppressions" ADD CONSTRAINT "supplier_preflight_suppressions_supplier_account_id_supplier_accounts_id_fk" FOREIGN KEY ("supplier_account_id") REFERENCES "public"."supplier_accounts"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supplier_preflight_suppressions" ADD CONSTRAINT "supplier_preflight_suppressions_sourcing_policy_id_supplier_sourcing_policies_id_fk" FOREIGN KEY ("sourcing_policy_id") REFERENCES "public"."supplier_sourcing_policies"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supplier_quote_shipping_options" ADD CONSTRAINT "supplier_quote_shipping_options_quote_id_supplier_quotes_id_fk" FOREIGN KEY ("quote_id") REFERENCES "public"."supplier_quotes"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supplier_quotes" ADD CONSTRAINT "supplier_quotes_supplier_id_suppliers_id_fk" FOREIGN KEY ("supplier_id") REFERENCES "public"."suppliers"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supplier_quotes" ADD CONSTRAINT "supplier_quotes_supplier_account_id_supplier_accounts_id_fk" FOREIGN KEY ("supplier_account_id") REFERENCES "public"."supplier_accounts"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supplier_quotes" ADD CONSTRAINT "supplier_quotes_sourcing_policy_id_supplier_sourcing_policies_id_fk" FOREIGN KEY ("sourcing_policy_id") REFERENCES "public"."supplier_sourcing_policies"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supplier_quotes" ADD CONSTRAINT "supplier_quotes_superseded_by_quote_id_supplier_quotes_id_fk" FOREIGN KEY ("superseded_by_quote_id") REFERENCES "public"."supplier_quotes"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supplier_reservations" ADD CONSTRAINT "supplier_reservations_quote_id_supplier_quotes_id_fk" FOREIGN KEY ("quote_id") REFERENCES "public"."supplier_quotes"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supplier_reservations" ADD CONSTRAINT "supplier_reservations_supplier_id_suppliers_id_fk" FOREIGN KEY ("supplier_id") REFERENCES "public"."suppliers"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supplier_reservations" ADD CONSTRAINT "supplier_reservations_supplier_account_id_supplier_accounts_id_fk" FOREIGN KEY ("supplier_account_id") REFERENCES "public"."supplier_accounts"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supplier_sourcing_attempts" ADD CONSTRAINT "supplier_sourcing_attempts_supplier_id_suppliers_id_fk" FOREIGN KEY ("supplier_id") REFERENCES "public"."suppliers"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supplier_sourcing_attempts" ADD CONSTRAINT "supplier_sourcing_attempts_supplier_account_id_supplier_accounts_id_fk" FOREIGN KEY ("supplier_account_id") REFERENCES "public"."supplier_accounts"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supplier_sourcing_attempts" ADD CONSTRAINT "supplier_sourcing_attempts_sourcing_policy_id_supplier_sourcing_policies_id_fk" FOREIGN KEY ("sourcing_policy_id") REFERENCES "public"."supplier_sourcing_policies"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supplier_sourcing_attempts" ADD CONSTRAINT "supplier_sourcing_attempts_quote_id_supplier_quotes_id_fk" FOREIGN KEY ("quote_id") REFERENCES "public"."supplier_quotes"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "supplier_call_leases_account_slot_key" ON "supplier_call_leases" USING btree ("supplier_account_id","slot");--> statement-breakpoint
CREATE INDEX "supplier_call_leases_account_free_idx" ON "supplier_call_leases" USING btree ("supplier_account_id","lease_until");--> statement-breakpoint
CREATE UNIQUE INDEX "supplier_preflight_health_account_key" ON "supplier_preflight_health" USING btree ("supplier_account_id");--> statement-breakpoint
CREATE UNIQUE INDEX "supplier_preflight_suppressions_live_key" ON "supplier_preflight_suppressions" USING btree ("suppression_key") WHERE "supplier_preflight_suppressions"."lifted_at" is null;--> statement-breakpoint
CREATE INDEX "supplier_preflight_suppressions_account_idx" ON "supplier_preflight_suppressions" USING btree ("supplier_account_id") WHERE "supplier_preflight_suppressions"."lifted_at" is null and "supplier_preflight_suppressions"."supplier_account_id" is not null;--> statement-breakpoint
CREATE INDEX "supplier_preflight_suppressions_market_idx" ON "supplier_preflight_suppressions" USING btree ("market_country") WHERE "supplier_preflight_suppressions"."lifted_at" is null and "supplier_preflight_suppressions"."market_country" is not null;--> statement-breakpoint
CREATE INDEX "supplier_preflight_suppressions_raised_idx" ON "supplier_preflight_suppressions" USING btree ("effective_from");--> statement-breakpoint
CREATE UNIQUE INDEX "supplier_quote_shipping_options_quote_service_key" ON "supplier_quote_shipping_options" USING btree ("quote_id","service_code");--> statement-breakpoint
CREATE INDEX "supplier_quote_shipping_options_quote_idx" ON "supplier_quote_shipping_options" USING btree ("quote_id","position");--> statement-breakpoint
CREATE UNIQUE INDEX "supplier_quotes_idempotency_key_key" ON "supplier_quotes" USING btree ("idempotency_key");--> statement-breakpoint
CREATE INDEX "supplier_quotes_offer_market_idx" ON "supplier_quotes" USING btree ("procurement_offer_id","destination_country","expires_at") WHERE "supplier_quotes"."status" = 'complete' and "supplier_quotes"."consumed_at" is null;--> statement-breakpoint
CREATE INDEX "supplier_quotes_checkout_group_idx" ON "supplier_quotes" USING btree ("checkout_group_id","created_at") WHERE "supplier_quotes"."checkout_group_id" is not null;--> statement-breakpoint
CREATE INDEX "supplier_quotes_order_idx" ON "supplier_quotes" USING btree ("order_id") WHERE "supplier_quotes"."order_id" is not null;--> statement-breakpoint
CREATE INDEX "supplier_quotes_account_idx" ON "supplier_quotes" USING btree ("supplier_account_id","created_at");--> statement-breakpoint
CREATE INDEX "supplier_quotes_exception_idx" ON "supplier_quotes" USING btree ("created_at") WHERE "supplier_quotes"."exception_kind" is not null;--> statement-breakpoint
CREATE INDEX "supplier_quotes_expiry_idx" ON "supplier_quotes" USING btree ("expires_at") WHERE "supplier_quotes"."consumed_at" is null and "supplier_quotes"."released_at" is null;--> statement-breakpoint
CREATE UNIQUE INDEX "supplier_reservations_quote_key" ON "supplier_reservations" USING btree ("quote_id");--> statement-breakpoint
CREATE UNIQUE INDEX "supplier_reservations_provider_key" ON "supplier_reservations" USING btree ("supplier_account_id","provider_reservation_id");--> statement-breakpoint
CREATE INDEX "supplier_reservations_expiry_idx" ON "supplier_reservations" USING btree ("provider_expires_at") WHERE "supplier_reservations"."consumed_at" is null and "supplier_reservations"."released_at" is null;--> statement-breakpoint
CREATE INDEX "supplier_reservations_account_idx" ON "supplier_reservations" USING btree ("supplier_account_id","reserved_at");--> statement-breakpoint
CREATE UNIQUE INDEX "supplier_sourcing_attempts_request_sequence_key" ON "supplier_sourcing_attempts" USING btree ("request_fingerprint","sequence");--> statement-breakpoint
CREATE INDEX "supplier_sourcing_attempts_checkout_group_idx" ON "supplier_sourcing_attempts" USING btree ("checkout_group_id","at") WHERE "supplier_sourcing_attempts"."checkout_group_id" is not null;--> statement-breakpoint
CREATE INDEX "supplier_sourcing_attempts_account_idx" ON "supplier_sourcing_attempts" USING btree ("supplier_account_id","at");--> statement-breakpoint
CREATE UNIQUE INDEX "supplier_sourcing_policies_key_version_key" ON "supplier_sourcing_policies" USING btree ("policy_key","version");--> statement-breakpoint
CREATE UNIQUE INDEX "supplier_sourcing_policies_one_active_per_key" ON "supplier_sourcing_policies" USING btree ("policy_key") WHERE "supplier_sourcing_policies"."status" = 'active';--> statement-breakpoint
-- ── Hand-written enforcement (#122) ───────────────────────────────────────────
-- drizzle-kit does not model triggers. See the header of this file for what
-- each one holds and what to do after a regeneration.

CREATE OR REPLACE FUNCTION mercaria_supplier_sourcing_policy_immutable()
RETURNS trigger AS $$
BEGIN
  -- A DRAFT is editable; anything published is frozen. Status may still move
  -- (active → superseded → retired) or a version could never be replaced.
  IF OLD.status = 'draft' THEN
    RETURN NEW;
  END IF;
  IF NEW.policy_key IS DISTINCT FROM OLD.policy_key
     OR NEW.version IS DISTINCT FROM OLD.version
     OR NEW.effective_start IS DISTINCT FROM OLD.effective_start
     OR NEW.effective_end IS DISTINCT FROM OLD.effective_end
     OR NEW.ranking_criteria IS DISTINCT FROM OLD.ranking_criteria
     OR NEW.required_capabilities IS DISTINCT FROM OLD.required_capabilities
     OR NEW.max_sourcing_attempts IS DISTINCT FROM OLD.max_sourcing_attempts
     OR NEW.max_supplier_share_bps IS DISTINCT FROM OLD.max_supplier_share_bps
     OR NEW.quote_ttl_seconds IS DISTINCT FROM OLD.quote_ttl_seconds
     OR NEW.provider_timeout_ms IS DISTINCT FROM OLD.provider_timeout_ms
     OR NEW.max_provider_concurrency IS DISTINCT FROM OLD.max_provider_concurrency
     OR NEW.max_provider_calls_per_minute IS DISTINCT FROM OLD.max_provider_calls_per_minute
     OR NEW.health_window_minutes IS DISTINCT FROM OLD.health_window_minutes
     OR NEW.health_minimum_samples IS DISTINCT FROM OLD.health_minimum_samples
     OR NEW.health_max_failure_bps IS DISTINCT FROM OLD.health_max_failure_bps
     OR NEW.health_suppression_minutes IS DISTINCT FROM OLD.health_suppression_minutes
     OR NEW.created_by_oxy_user_id IS DISTINCT FROM OLD.created_by_oxy_user_id THEN
    RAISE EXCEPTION 'supplier_sourcing_policies is immutable once published: publish a new version'
      USING ERRCODE = 'restrict_violation';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;--> statement-breakpoint
CREATE TRIGGER mercaria_supplier_sourcing_policy_immutable
BEFORE UPDATE ON "supplier_sourcing_policies"
FOR EACH ROW EXECUTE FUNCTION mercaria_supplier_sourcing_policy_immutable();--> statement-breakpoint

CREATE OR REPLACE FUNCTION mercaria_supplier_quote_immutable()
RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'supplier_quotes cannot be deleted: a quote is the evidence a charge was made against'
      USING ERRCODE = 'restrict_violation';
  END IF;

  -- Identity, request and ANSWER never change. Listed explicitly rather than as
  -- "everything except the usage columns", so a column added later is frozen by
  -- DEFAULT only if somebody adds it here — which is the direction that fails
  -- safe for a record, and the direction a reviewer will notice.
  IF NEW.idempotency_key IS DISTINCT FROM OLD.idempotency_key
     OR NEW.request_fingerprint IS DISTINCT FROM OLD.request_fingerprint
     OR NEW.supplier_id IS DISTINCT FROM OLD.supplier_id
     OR NEW.supplier_account_id IS DISTINCT FROM OLD.supplier_account_id
     OR NEW.environment IS DISTINCT FROM OLD.environment
     OR NEW.provider IS DISTINCT FROM OLD.provider
     OR NEW.declared_capabilities IS DISTINCT FROM OLD.declared_capabilities
     OR NEW.procurement_offer_id IS DISTINCT FROM OLD.procurement_offer_id
     OR NEW.supplier_sku IS DISTINCT FROM OLD.supplier_sku
     OR NEW.quantity IS DISTINCT FROM OLD.quantity
     OR NEW.checkout_group_id IS DISTINCT FROM OLD.checkout_group_id
     OR NEW.requested_currency IS DISTINCT FROM OLD.requested_currency
     OR NEW.destination_country IS DISTINCT FROM OLD.destination_country
     OR NEW.destination_region IS DISTINCT FROM OLD.destination_region
     OR NEW.identity_confirmation IS DISTINCT FROM OLD.identity_confirmation
     OR NEW.availability IS DISTINCT FROM OLD.availability
     OR NEW.unit_cost_amount IS DISTINCT FROM OLD.unit_cost_amount
     OR NEW.shipping_cost_amount IS DISTINCT FROM OLD.shipping_cost_amount
     OR NEW.shipping_basis IS DISTINCT FROM OLD.shipping_basis
     OR NEW.selected_shipping_service_code IS DISTINCT FROM OLD.selected_shipping_service_code
     OR NEW.tax_amount IS DISTINCT FROM OLD.tax_amount
     OR NEW.duty_amount IS DISTINCT FROM OLD.duty_amount
     OR NEW.status IS DISTINCT FROM OLD.status
     OR NEW.block_reasons IS DISTINCT FROM OLD.block_reasons
     OR NEW.exception_kind IS DISTINCT FROM OLD.exception_kind
     OR NEW.quoted_at IS DISTINCT FROM OLD.quoted_at
     OR NEW.expires_at IS DISTINCT FROM OLD.expires_at THEN
    RAISE EXCEPTION 'supplier_quotes records what a supplier said and is immutable; re-quote instead'
      USING ERRCODE = 'restrict_violation';
  END IF;

  -- Usage is ONE-WAY. Each of these moves NULL → a value exactly once, which is
  -- what makes "a quote consumed by one checkout cannot be attached to another"
  -- (#122 concurrency 3) true of a service bug and of `psql` alike.
  IF OLD.consumed_at IS NOT NULL AND NEW.consumed_at IS DISTINCT FROM OLD.consumed_at THEN
    RAISE EXCEPTION 'supplier_quotes.consumed_at is set once and never re-pointed'
      USING ERRCODE = 'restrict_violation';
  END IF;
  IF OLD.consumed_by_checkout_group_id IS NOT NULL
     AND NEW.consumed_by_checkout_group_id IS DISTINCT FROM OLD.consumed_by_checkout_group_id THEN
    RAISE EXCEPTION 'a supplier quote consumed by one checkout cannot be attached to another'
      USING ERRCODE = 'restrict_violation';
  END IF;
  IF OLD.released_at IS NOT NULL AND NEW.released_at IS DISTINCT FROM OLD.released_at THEN
    RAISE EXCEPTION 'supplier_quotes.released_at is set once'
      USING ERRCODE = 'restrict_violation';
  END IF;
  IF OLD.superseded_by_quote_id IS NOT NULL
     AND NEW.superseded_by_quote_id IS DISTINCT FROM OLD.superseded_by_quote_id THEN
    RAISE EXCEPTION 'supplier_quotes.superseded_by_quote_id is set once'
      USING ERRCODE = 'restrict_violation';
  END IF;
  -- `order_id` is the ONE correlation that may be filled in later (the retail
  -- order does not exist when the quote is taken — ADR 0004 D4 step 1), and it
  -- may be filled in only once.
  IF OLD.order_id IS NOT NULL AND NEW.order_id IS DISTINCT FROM OLD.order_id THEN
    RAISE EXCEPTION 'supplier_quotes.order_id is set once and never re-pointed'
      USING ERRCODE = 'restrict_violation';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;--> statement-breakpoint
CREATE TRIGGER mercaria_supplier_quote_immutable
BEFORE UPDATE OR DELETE ON "supplier_quotes"
FOR EACH ROW EXECUTE FUNCTION mercaria_supplier_quote_immutable();--> statement-breakpoint

CREATE OR REPLACE FUNCTION mercaria_supplier_reservation_immutable()
RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'supplier_reservations cannot be deleted: a hold Mercaria took is a fact about a supplier''s stock'
      USING ERRCODE = 'restrict_violation';
  END IF;

  -- These three are what make the row EVIDENCE of a supplier's commitment
  -- rather than a local claim. Nothing may edit them, ever.
  IF NEW.provider_reservation_id IS DISTINCT FROM OLD.provider_reservation_id
     OR NEW.provider_expires_at IS DISTINCT FROM OLD.provider_expires_at
     OR NEW.declared_capabilities IS DISTINCT FROM OLD.declared_capabilities
     OR NEW.quote_id IS DISTINCT FROM OLD.quote_id
     OR NEW.supplier_id IS DISTINCT FROM OLD.supplier_id
     OR NEW.supplier_account_id IS DISTINCT FROM OLD.supplier_account_id
     OR NEW.supplier_sku IS DISTINCT FROM OLD.supplier_sku
     OR NEW.quantity IS DISTINCT FROM OLD.quantity
     OR NEW.reserved_at IS DISTINCT FROM OLD.reserved_at
     OR NEW.single_use IS DISTINCT FROM OLD.single_use THEN
    RAISE EXCEPTION 'supplier_reservations records a supplier''s own commitment and is immutable'
      USING ERRCODE = 'restrict_violation';
  END IF;

  IF OLD.consumed_at IS NOT NULL AND NEW.consumed_at IS DISTINCT FROM OLD.consumed_at THEN
    RAISE EXCEPTION 'a single-use supplier reservation cannot be consumed twice'
      USING ERRCODE = 'restrict_violation';
  END IF;
  IF OLD.released_at IS NOT NULL AND NEW.released_at IS DISTINCT FROM OLD.released_at THEN
    RAISE EXCEPTION 'supplier_reservations.released_at is set once'
      USING ERRCODE = 'restrict_violation';
  END IF;
  -- The retry counter only ever climbs: a reset would let a bounded retry run
  -- forever, which is the one thing the bound exists to prevent.
  IF NEW.release_attempts < OLD.release_attempts THEN
    RAISE EXCEPTION 'supplier_reservations.release_attempts cannot decrease'
      USING ERRCODE = 'restrict_violation';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;--> statement-breakpoint
CREATE TRIGGER mercaria_supplier_reservation_immutable
BEFORE UPDATE OR DELETE ON "supplier_reservations"
FOR EACH ROW EXECUTE FUNCTION mercaria_supplier_reservation_immutable();--> statement-breakpoint

CREATE OR REPLACE FUNCTION mercaria_supplier_quote_shipping_option_append_only()
RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'supplier_quote_shipping_options is append-only: % is not permitted', TG_OP
    USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;--> statement-breakpoint
CREATE TRIGGER mercaria_supplier_quote_shipping_option_append_only
BEFORE UPDATE OR DELETE ON "supplier_quote_shipping_options"
FOR EACH ROW EXECUTE FUNCTION mercaria_supplier_quote_shipping_option_append_only();--> statement-breakpoint

CREATE OR REPLACE FUNCTION mercaria_supplier_sourcing_attempt_append_only()
RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'supplier_sourcing_attempts is append-only: % is not permitted', TG_OP
    USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;--> statement-breakpoint
CREATE TRIGGER mercaria_supplier_sourcing_attempt_append_only
BEFORE UPDATE OR DELETE ON "supplier_sourcing_attempts"
FOR EACH ROW EXECUTE FUNCTION mercaria_supplier_sourcing_attempt_append_only();
