-- oxy:deploy-phase=post
--
-- #477. Both constraints reached production with a BARE `.` where a literal dot
-- was meant, so each admits exactly what it exists to refuse: a POSIX `.`
-- matches any character, making `foo bar` and `foo/bar` legal product-type keys
-- and `axcom` a legal advertiser host. Cause in both cases is that the pattern
-- was an inline drizzle template literal, whose COOKED strings drop `\.` to `.`
-- before drizzle sees it. Both now render through `sql.raw`.
--
-- `post`, not `pre`, because both statements NARROW what the column accepts.
-- Applied `pre` the tightened CHECK is in force while the PREVIOUS image is
-- still serving, so any write that image is prepared to make and the new
-- constraint refuses becomes a 500 on the running deployment. `post` puts the
-- new image in front of the narrowing and costs only the rollout's worth of
-- today's behaviour. This is also `migrate.ts`'s own one-line definition —
-- anything that takes something away — and a DROP CONSTRAINT takes it away.
--
-- Safe to apply, and this is a STRUCTURAL argument over the writers rather than
-- a row count — there is no production database credential on any developer
-- host and the RDS instance is internal-only, so no count was taken and none is
-- claimed. What is claimed is censused:
--
--   `product_type_definitions.key` has exactly one production writer,
--   `insertProductTypeDefinition`, whose only production caller is
--   `scripts/seed-verticals/apply.ts`. It writes `nsKey(namespaceFor(token),
--   pkg.key)`; `namespaceFor` folds everything outside `[a-z0-9]` to `_` and
--   refuses a leading digit, and the shipped package keys are `smartphone`,
--   `athletic_footwear` and `brake_pad`. Every producible key is therefore
--   `[a-z][a-z0-9_]*`, a strict subset of the pattern. Pinned by
--   `verticals-package-controls.test.ts`, so a fourth package with a dotted or
--   hyphenated key fails the build.
--
--   `awin_advertisers.declared_host` has NO production writer that supplies a
--   value at all. `discoverAwinAdvertiser` is the only statement that sets the
--   column; the primary discovery path passes no `declaredHost`, so it stores
--   NULL, and `discoverAwinAdvertiserSeenOnly` re-passes the row's own
--   read-back. No raw SQL and no migration writes it. Every production row is
--   NULL, which `is null or …` admits unconditionally.
--
-- The failure mode being accepted: if a violating row does exist, the ADD
-- CONSTRAINT fails at apply time and the deploy stops. Loud, and the safe
-- direction for an unknown of this kind.
--
-- There are NO hand-written statements below, so a regeneration of this file is
-- safe. The patterns live in `PRODUCT_TYPE_KEY_PATTERN` and
-- `AWIN_DECLARED_HOST_PATTERN`; regenerating re-renders them from there.
ALTER TABLE "awin_advertisers" DROP CONSTRAINT "awin_advertisers_declared_host_shape_check";--> statement-breakpoint
ALTER TABLE "product_type_definitions" DROP CONSTRAINT "product_type_definitions_key_shape_check";--> statement-breakpoint
ALTER TABLE "awin_advertisers" ADD CONSTRAINT "awin_advertisers_declared_host_shape_check" CHECK ("awin_advertisers"."declared_host" is null
          or "awin_advertisers"."declared_host" ~ '^[a-z0-9]([a-z0-9-]*[a-z0-9])?([.][a-z0-9]([a-z0-9-]*[a-z0-9])?)+$');--> statement-breakpoint
ALTER TABLE "product_type_definitions" ADD CONSTRAINT "product_type_definitions_key_shape_check" CHECK ("product_type_definitions"."key" ~ '^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)*$');