/**
 * The expiry sweep LOOP, against a REAL Postgres database.
 *
 * `notifications.realdb.test.ts` already pins the notification target's own rule
 * (90 days past the DISMISSAL, never past creation). This file tests the thing
 * above it: that `sweepExpiredRowsOnce` — what the scheduler in
 * `db/expirySweeper.ts` calls on every tick — actually runs over EVERY registry
 * entry, and that the two moderation targets and the two payment ones delete
 * what they should and keep what they should.
 *
 * ## Why this needs its own file rather than one more case next door
 *
 * The registry and the sweep mechanism both existed before anything called them.
 * A registry with no scheduler is not a partially-working feature, it is a list:
 * Postgres has no TTL index, so an unscheduled target grows FOREVER with no
 * error, no failing test and no symptom until disk. The thing that used to do
 * this work was a property of the Mongo SERVER, so nothing in this codebase went
 * missing when it was ported away — there is no deleted call site for a reviewer
 * to notice. That is precisely the class of gap a test has to close, because
 * review cannot.
 *
 * So the assertions here are about the WIRING as much as the SQL: every fixture
 * is swept through the same entry point production uses, and the vacuity floor
 * below fails if the registry ever stops naming all five tables.
 *
 * ## Every fixture pair spans the distinction its target exists to make
 *
 * A sweep test that only seeds expired rows cannot tell a correct predicate from
 * `DELETE FROM <table>`. Each block seeds one row that must GO and one that must
 * STAY, differing only in the column the target measures.
 */

import { afterAll, afterEach, beforeAll, describe, expect, it } from 'vitest';
import { eq, getTableName, inArray } from 'drizzle-orm';
import { uuidv7 } from '@oxyhq/db';
import { closePostgres, connectPostgres, type Database } from '../postgres.js';
import { EXPIRY_TARGETS } from '../expiryTargets.js';
import { sweepExpiredRowsOnce } from '../expirySweeper.js';
import { moderationEvents, moderationOutboxes } from '../schema/moderation.js';
import { notifications } from '../schema/notifications.js';
import { paymentOutboxes, paymentProviderEvents } from '../schema/payments.js';

let db: Database;

/** An hour in the past — comfortably past any `expires_at` deadline. */
const EXPIRED_AT = new Date(Date.now() - 60 * 60 * 1_000);
/** An hour in the future — comfortably short of one. */
const NOT_YET_EXPIRED_AT = new Date(Date.now() + 60 * 60 * 1_000);
/** 91 days ago: one day past the dismissed-notification retention. */
const PAST_NOTIFICATION_RETENTION = new Date(Date.now() - 91 * 24 * 60 * 60 * 1_000);

const outboxIds: string[] = [];
const eventIds: string[] = [];
const notificationUserIds: string[] = [];
const paymentOutboxIds: string[] = [];
/** Tracked by `provider_event_id`: the row's own id is generated by the table. */
const providerEventIds: string[] = [];

/**
 * An outbox row with a caller-supplied deadline.
 *
 * The id is minted per row rather than derived, unlike production's deterministic
 * `moderation:report.submit:<id>`: what is under test is the sweep, and two tests
 * converging on one row would make a deletion look like a survival.
 */
async function makeOutboxRow(expiresAt: Date): Promise<string> {
  const id = `sweep-outbox-${uuidv7()}`;
  outboxIds.push(id);
  await db.insert(moderationOutboxes).values({
    id,
    kind: 'report.submit',
    payload: { reportId: uuidv7() },
    status: 'pending',
    attempts: 0,
    availableAt: new Date(),
    expiresAt,
  });
  return id;
}

async function makeEventClaim(expiresAt: Date): Promise<string> {
  const id = `sweep-event-${uuidv7()}`;
  eventIds.push(id);
  await db.insert(moderationEvents).values({
    id,
    eventType: 'webhook',
    claimedAt: new Date(),
    expiresAt,
  });
  return id;
}

async function makeNotification(dismissedAt: Date | null): Promise<string> {
  const oxyUserId = `sweep-notif-${uuidv7()}`;
  notificationUserIds.push(oxyUserId);
  const [row] = await db
    .insert(notifications)
    .values({
      oxyUserId,
      type: 'order_placed',
      title: 'Order placed',
      body: 'Your order has been placed.',
      channels: ['in_app'],
      deliveryStatus: { in_app: 'sent' },
      // The CHECK ties these two together, so a dismissed fixture must set both.
      status: dismissedAt === null ? 'sent' : 'dismissed',
      priority: 'normal',
      ...(dismissedAt === null ? {} : { dismissedAt }),
    })
    .returning({ id: notifications.id });
  return row.id;
}

/**
 * A payment outbox row with a caller-supplied deadline.
 *
 * Born in Postgres rather than ported from a Mongo TTL index, but swept by the
 * same loop for the same reason: nothing else deletes a delivered event.
 */
async function makePaymentOutboxRow(expiresAt: Date): Promise<string> {
  const id = `sweep-payment-outbox-${uuidv7()}`;
  paymentOutboxIds.push(id);
  await db.insert(paymentOutboxes).values({
    id,
    eventType: 'payment_succeeded',
    payload: { paymentId: uuidv7() },
    status: 'pending',
    attempts: 0,
    availableAt: new Date(),
    expiresAt,
  });
  return id;
}

/** A provider-event dedupe row with a caller-supplied deadline. */
async function makeProviderEventRow(expiresAt: Date): Promise<string> {
  const providerEventId = `sweep-provider-event-${uuidv7()}`;
  providerEventIds.push(providerEventId);
  const [row] = await db
    .insert(paymentProviderEvents)
    .values({
      provider: 'mock',
      providerEventId,
      type: 'payment.succeeded',
      livemode: false,
      objectIds: {},
      payloadSummary: {},
      receivedAt: new Date(),
      status: 'processed',
      attempts: 1,
      expiresAt,
    })
    .returning({ id: paymentProviderEvents.id });
  return row.id;
}

async function paymentOutboxExists(id: string): Promise<boolean> {
  const rows = await db
    .select({ id: paymentOutboxes.id })
    .from(paymentOutboxes)
    .where(eq(paymentOutboxes.id, id));
  return rows.length === 1;
}

async function providerEventExists(id: string): Promise<boolean> {
  const rows = await db
    .select({ id: paymentProviderEvents.id })
    .from(paymentProviderEvents)
    .where(eq(paymentProviderEvents.id, id));
  return rows.length === 1;
}

async function outboxExists(id: string): Promise<boolean> {
  const rows = await db
    .select({ id: moderationOutboxes.id })
    .from(moderationOutboxes)
    .where(eq(moderationOutboxes.id, id));
  return rows.length === 1;
}

async function eventExists(id: string): Promise<boolean> {
  const rows = await db
    .select({ id: moderationEvents.id })
    .from(moderationEvents)
    .where(eq(moderationEvents.id, id));
  return rows.length === 1;
}

async function notificationExists(id: string): Promise<boolean> {
  const rows = await db
    .select({ id: notifications.id })
    .from(notifications)
    .where(eq(notifications.id, id));
  return rows.length === 1;
}

beforeAll(async () => {
  db = await connectPostgres();
}, 120_000);

afterEach(async () => {
  const outbox = outboxIds.splice(0);
  const events = eventIds.splice(0);
  const users = notificationUserIds.splice(0);
  if (outbox.length > 0) {
    await db.delete(moderationOutboxes).where(inArray(moderationOutboxes.id, outbox));
  }
  if (events.length > 0) {
    await db.delete(moderationEvents).where(inArray(moderationEvents.id, events));
  }
  if (users.length > 0) {
    await db.delete(notifications).where(inArray(notifications.oxyUserId, users));
  }
  const paymentOutbox = paymentOutboxIds.splice(0);
  const providerEvents = providerEventIds.splice(0);
  if (paymentOutbox.length > 0) {
    await db.delete(paymentOutboxes).where(inArray(paymentOutboxes.id, paymentOutbox));
  }
  if (providerEvents.length > 0) {
    await db
      .delete(paymentProviderEvents)
      .where(inArray(paymentProviderEvents.providerEventId, providerEvents));
  }
});

afterAll(async () => {
  await closePostgres();
});

describe('the registry the sweeper runs over', () => {
  it('names every table the sweeper is responsible for, and nothing else', () => {
    // The vacuity floor for every case below: a sweep over an empty or shrunken
    // registry deletes nothing, and "the row survived" would then pass for the
    // wrong reason. Pinning the exact set also fails a table added to the
    // registry without a case here, rather than letting it ride untested.
    //
    // Three carried a Mongo TTL index; the two payment tables were born in
    // Postgres, where there is no TTL index to carry, which is precisely why
    // they need this loop.
    expect(EXPIRY_TARGETS.map((target) => getTableName(target.table)).sort()).toEqual([
      'moderation_events',
      'moderation_outboxes',
      'notifications',
      'payment_outboxes',
      'payment_provider_events',
    ]);
  });

  it('gives every target a reason, since a registry entry authorises a DELETE', () => {
    for (const target of EXPIRY_TARGETS) {
      expect(target.reason.length, `${getTableName(target.table)} has no reason`).toBeGreaterThan(0);
    }
  });
});

describe('sweepExpiredRowsOnce — the tick the scheduler runs', () => {
  it('reaps an expired outbox row and leaves one whose deadline has not passed', async () => {
    const expired = await makeOutboxRow(EXPIRED_AT);
    const live = await makeOutboxRow(NOT_YET_EXPIRED_AT);

    await sweepExpiredRowsOnce();

    expect(await outboxExists(expired), 'the expired outbox row survived').toBe(false);
    expect(await outboxExists(live), 'a live outbox row was reaped').toBe(true);
  });

  it('reaps an expired webhook dedupe claim and leaves a live one', async () => {
    const expired = await makeEventClaim(EXPIRED_AT);
    const live = await makeEventClaim(NOT_YET_EXPIRED_AT);

    await sweepExpiredRowsOnce();

    expect(await eventExists(expired), 'the expired claim survived').toBe(false);
    // A claim must outlive every redelivery of its event; reaping one early
    // lets a duplicate decision be processed a second time.
    expect(await eventExists(live), 'a live dedupe claim was reaped').toBe(true);
  });

  it('reaps a long-dismissed notification and leaves an undismissed one', async () => {
    const dismissed = await makeNotification(PAST_NOTIFICATION_RETENTION);
    const neverDismissed = await makeNotification(null);

    await sweepExpiredRowsOnce();

    expect(await notificationExists(dismissed), 'the dismissed notification survived').toBe(false);
    expect(await notificationExists(neverDismissed), 'an undismissed notification was reaped').toBe(
      true,
    );
  });

  it('reaps an expired payment outbox row and leaves one whose deadline has not passed', async () => {
    const expired = await makePaymentOutboxRow(EXPIRED_AT);
    const live = await makePaymentOutboxRow(NOT_YET_EXPIRED_AT);

    await sweepExpiredRowsOnce();

    expect(await paymentOutboxExists(expired), 'the expired payment event survived').toBe(false);
    expect(await paymentOutboxExists(live), 'a live payment event was reaped').toBe(true);
  });

  it('reaps an expired provider-event dedupe row and leaves a live one', async () => {
    const expired = await makeProviderEventRow(EXPIRED_AT);
    const live = await makeProviderEventRow(NOT_YET_EXPIRED_AT);

    await sweepExpiredRowsOnce();

    expect(await providerEventExists(expired), 'the expired provider event survived').toBe(false);
    // Same reasoning as the moderation dedupe claim above: the row must outlive
    // every redelivery of its event, or a duplicate charge notification is
    // applied a second time.
    expect(await providerEventExists(live), 'a live provider event was reaped').toBe(true);
  });

  it('covers all five targets in ONE tick, not just the first', async () => {
    // The case the five above cannot make between them: each passes if the
    // sweep runs only its own target. Seeding one doomed row per table and
    // sweeping once is what proves the loop does not stop early — which is
    // exactly what a `return` in place of a `continue`, or a sweep of
    // `EXPIRY_TARGETS[0]`, would do.
    const outbox = await makeOutboxRow(EXPIRED_AT);
    const event = await makeEventClaim(EXPIRED_AT);
    const notification = await makeNotification(PAST_NOTIFICATION_RETENTION);
    const paymentOutbox = await makePaymentOutboxRow(EXPIRED_AT);
    const providerEvent = await makeProviderEventRow(EXPIRED_AT);

    await sweepExpiredRowsOnce();

    expect(await outboxExists(outbox)).toBe(false);
    expect(await eventExists(event)).toBe(false);
    expect(await notificationExists(notification)).toBe(false);
    expect(await paymentOutboxExists(paymentOutbox)).toBe(false);
    expect(await providerEventExists(providerEvent)).toBe(false);
  });
});
