/**
 * The expiry sweep LOOP, against a REAL Postgres database.
 *
 * `notifications.realdb.test.ts` already pins the notification target's own rule
 * (90 days past the DISMISSAL, never past creation). This file tests the thing
 * above it: that `sweepExpiredRowsOnce` — what the scheduler in
 * `db/expirySweeper.ts` calls on every tick — actually runs over EVERY registry
 * entry, and that the two moderation targets and the two payment ones delete
 * what they should and keep what they should.
 *
 * ## Why this needs its own file rather than one more case next door
 *
 * The registry and the sweep mechanism both existed before anything called them.
 * A registry with no scheduler is not a partially-working feature, it is a list:
 * Postgres has no TTL index, so an unscheduled target grows FOREVER with no
 * error, no failing test and no symptom until disk. The thing that used to do
 * this work was a property of the Mongo SERVER, so nothing in this codebase went
 * missing when it was ported away — there is no deleted call site for a reviewer
 * to notice. That is precisely the class of gap a test has to close, because
 * review cannot.
 *
 * So the assertions here are about the WIRING as much as the SQL: every fixture
 * is swept through the same entry point production uses, and the vacuity floor
 * below fails if the registry ever stops naming all five tables.
 *
 * ## Every fixture pair spans the distinction its target exists to make
 *
 * A sweep test that only seeds expired rows cannot tell a correct predicate from
 * `DELETE FROM <table>`. Each block seeds one row that must GO and one that must
 * STAY, differing only in the column the target measures.
 */

import { afterAll, afterEach, beforeAll, describe, expect, it } from 'vitest';
import { eq, getTableName, inArray } from 'drizzle-orm';
import { uuidv7 } from '@oxyhq/db';
import { closePostgres, connectPostgres, type Database } from '../postgres.js';
import { EXPIRY_TARGETS } from '../expiryTargets.js';
import { sweepExpiredRowsOnce } from '../expirySweeper.js';
import { guestSessions } from '../schema/guests.js';
import { moderationEvents, moderationOutboxes } from '../schema/moderation.js';
import { notifications } from '../schema/notifications.js';
import { paymentOutboxes, paymentProviderEvents } from '../schema/payments.js';
import {
  referralCodes,
  referralPartners,
  referralPrograms,
  referralTouches,
} from '../schema/referrals.js';

let db: Database;

/** An hour in the past — comfortably past any `expires_at` deadline. */
const EXPIRED_AT = new Date(Date.now() - 60 * 60 * 1_000);
/** An hour in the future — comfortably short of one. */
const NOT_YET_EXPIRED_AT = new Date(Date.now() + 60 * 60 * 1_000);
/**
 * `available_at` for every outbox fixture: an hour ahead, so no fixture is ever
 * DUE. The sweep selects on `expires_at` alone, so this changes nothing under
 * test — but the database is shared and vitest runs files in parallel, and a
 * sibling file's dispatcher-style claim (`moderation-writes.realdb.test.ts`
 * claims without an event id) selects on `status = 'pending' AND available_at <=
 * now`. A due fixture here is claimable there, and a `sweep-outbox-*` id has
 * surfaced inside that file's claim assertions (#151). Never-due fixtures cannot
 * cross that predicate, whatever new claim-shaped test a sibling grows.
 */
const NEVER_DUE_AT = NOT_YET_EXPIRED_AT;
/** 91 days ago: one day past the dismissed-notification retention. */
const PAST_NOTIFICATION_RETENTION = new Date(Date.now() - 91 * 24 * 60 * 60 * 1_000);
/** 8 days ago: one day past the guest-session 7-day purge grace (ADR 0003 D11). */
const PAST_GUEST_PURGE_GRACE = new Date(Date.now() - 8 * 24 * 60 * 60 * 1_000);
/** 1 day ago: expired/revoked, but still INSIDE the 7-day purge grace. */
const WITHIN_GUEST_PURGE_GRACE = new Date(Date.now() - 24 * 60 * 60 * 1_000);

const outboxIds: string[] = [];
const eventIds: string[] = [];
const notificationUserIds: string[] = [];
const paymentOutboxIds: string[] = [];
/** Tracked by `provider_event_id`: the row's own id is generated by the table. */
const providerEventIds: string[] = [];
const guestSessionIds: string[] = [];
const touchIds: string[] = [];
/** The one code/partner/program-version chain every touch fixture hangs off. */
let touchChain: { programVersionId: string; partnerId: string; codeId: string } | null = null;

/**
 * An outbox row with a caller-supplied deadline.
 *
 * The id is minted per row rather than derived, unlike production's deterministic
 * `moderation:report.submit:<id>`: what is under test is the sweep, and two tests
 * converging on one row would make a deletion look like a survival.
 */
async function makeOutboxRow(expiresAt: Date): Promise<string> {
  const id = `sweep-outbox-${uuidv7()}`;
  outboxIds.push(id);
  await db.insert(moderationOutboxes).values({
    id,
    kind: 'report.submit',
    payload: { reportId: uuidv7() },
    status: 'pending',
    attempts: 0,
    availableAt: NEVER_DUE_AT,
    expiresAt,
  });
  return id;
}

async function makeEventClaim(expiresAt: Date): Promise<string> {
  const id = `sweep-event-${uuidv7()}`;
  eventIds.push(id);
  await db.insert(moderationEvents).values({
    id,
    eventType: 'webhook',
    claimedAt: new Date(),
    expiresAt,
  });
  return id;
}

async function makeNotification(dismissedAt: Date | null): Promise<string> {
  const oxyUserId = `sweep-notif-${uuidv7()}`;
  notificationUserIds.push(oxyUserId);
  const [row] = await db
    .insert(notifications)
    .values({
      oxyUserId,
      type: 'order_placed',
      title: 'Order placed',
      body: 'Your order has been placed.',
      channels: ['in_app'],
      deliveryStatus: { in_app: 'sent' },
      // The CHECK ties these two together, so a dismissed fixture must set both.
      status: dismissedAt === null ? 'sent' : 'dismissed',
      priority: 'normal',
      ...(dismissedAt === null ? {} : { dismissedAt }),
    })
    .returning({ id: notifications.id });
  return row.id;
}

/**
 * A payment outbox row with a caller-supplied deadline.
 *
 * Born in Postgres rather than ported from a Mongo TTL index, but swept by the
 * same loop for the same reason: nothing else deletes a delivered event.
 */
async function makePaymentOutboxRow(expiresAt: Date): Promise<string> {
  const id = `sweep-payment-outbox-${uuidv7()}`;
  paymentOutboxIds.push(id);
  await db.insert(paymentOutboxes).values({
    id,
    eventType: 'payment_succeeded',
    payload: { paymentId: uuidv7() },
    status: 'pending',
    attempts: 0,
    availableAt: NEVER_DUE_AT,
    expiresAt,
  });
  return id;
}

/** A provider-event dedupe row with a caller-supplied deadline. */
async function makeProviderEventRow(expiresAt: Date): Promise<string> {
  const providerEventId = `sweep-provider-event-${uuidv7()}`;
  providerEventIds.push(providerEventId);
  const [row] = await db
    .insert(paymentProviderEvents)
    .values({
      provider: 'mock',
      providerEventId,
      type: 'payment.succeeded',
      livemode: false,
      objectIds: {},
      payloadSummary: {},
      receivedAt: new Date(),
      status: 'processed',
      attempts: 1,
      expiresAt,
    })
    .returning({ id: paymentProviderEvents.id });
  return row.id;
}

/**
 * A guest session with caller-supplied lifecycle timestamps (ADR 0003 D11).
 *
 * The `tokenHash` is a synthetic unique marker, never a real token's hash —
 * what is under test is the purge predicate, and the resolver is not in play.
 */
async function makeGuestSessionRow(input: {
  expiresAt: Date;
  revokedAt?: Date;
}): Promise<string> {
  const [row] = await db
    .insert(guestSessions)
    .values({
      tokenHash: `sweep-guest-${uuidv7()}`,
      clientClass: 'other',
      lastSeenAt: new Date(),
      expiresAt: input.expiresAt,
      ...(input.revokedAt === undefined ? {} : { revokedAt: input.revokedAt }),
    })
    .returning({ id: guestSessions.id });
  guestSessionIds.push(row.id);
  return row.id;
}

async function guestSessionExists(id: string): Promise<boolean> {
  const rows = await db
    .select({ id: guestSessions.id })
    .from(guestSessions)
    .where(eq(guestSessions.id, id));
  return rows.length === 1;
}

/**
 * A referral touch with a caller-supplied deadline (#142). The touch's own
 * CHECK orders `occurred < window expiry <= expires`, so both fixture shapes
 * derive the earlier two from the deadline rather than from "now".
 */
async function makeReferralTouchRow(expiresAt: Date): Promise<string> {
  if (touchChain === null) {
    const [program] = await db
      .insert(referralPrograms)
      .values({
        programId: `sweep-prog-${uuidv7()}`,
        version: 1,
        name: 'Sweep fixture program',
        description: 'fixture',
        publicTermsSummary: 'fixture',
        family: 'buyer_referral',
        eligiblePartnerTypes: ['user'],
        eligibleSubjectKinds: ['oxy_user'],
        attributionPolicy: 'last_touch',
        attributionWindowDays: 30,
        qualifyingEventPolicy: 'first_qualifying_paid_order',
        commissionRuleRef: 'sweep-rule',
        holdDays: 60,
        payoutPolicyRef: 'sweep-payout',
        termsVersion: 't1',
        disclosureVersion: 'd1',
        createdByOxyUserId: `sweep-op-${uuidv7()}`,
      })
      .returning({ id: referralPrograms.id });
    const [partner] = await db
      .insert(referralPartners)
      .values({
        ownerType: 'user',
        ownerId: `sweep-partner-${uuidv7()}`,
        displayName: 'Sweep partner',
        state: 'approved',
        approvedAt: new Date(),
      })
      .returning({ id: referralPartners.id });
    const [code] = await db
      .insert(referralCodes)
      .values({
        partnerId: partner.id,
        programVersionId: program.id,
        code: `swp-${uuidv7().replace(/-/g, '').slice(0, 20)}`,
      })
      .returning({ id: referralCodes.id });
    touchChain = { programVersionId: program.id, partnerId: partner.id, codeId: code.id };
  }
  const [row] = await db
    .insert(referralTouches)
    .values({
      programVersionId: touchChain.programVersionId,
      partnerId: touchChain.partnerId,
      codeId: touchChain.codeId,
      touchKind: 'code_entry_in_app',
      occurredAt: new Date(expiresAt.getTime() - 2 * 60 * 60 * 1_000),
      clientSurface: 'web',
      actorKind: 'oxy_user',
      oxyUserId: `sweep-toucher-${uuidv7()}`,
      consentMode: 'granted',
      attributionWindowExpiresAt: new Date(expiresAt.getTime() - 60 * 60 * 1_000),
      expiresAt,
    })
    .returning({ id: referralTouches.id });
  touchIds.push(row.id);
  return row.id;
}

async function touchExists(id: string): Promise<boolean> {
  const rows = await db
    .select({ id: referralTouches.id })
    .from(referralTouches)
    .where(eq(referralTouches.id, id));
  return rows.length === 1;
}

async function paymentOutboxExists(id: string): Promise<boolean> {
  const rows = await db
    .select({ id: paymentOutboxes.id })
    .from(paymentOutboxes)
    .where(eq(paymentOutboxes.id, id));
  return rows.length === 1;
}

async function providerEventExists(id: string): Promise<boolean> {
  const rows = await db
    .select({ id: paymentProviderEvents.id })
    .from(paymentProviderEvents)
    .where(eq(paymentProviderEvents.id, id));
  return rows.length === 1;
}

async function outboxExists(id: string): Promise<boolean> {
  const rows = await db
    .select({ id: moderationOutboxes.id })
    .from(moderationOutboxes)
    .where(eq(moderationOutboxes.id, id));
  return rows.length === 1;
}

async function eventExists(id: string): Promise<boolean> {
  const rows = await db
    .select({ id: moderationEvents.id })
    .from(moderationEvents)
    .where(eq(moderationEvents.id, id));
  return rows.length === 1;
}

async function notificationExists(id: string): Promise<boolean> {
  const rows = await db
    .select({ id: notifications.id })
    .from(notifications)
    .where(eq(notifications.id, id));
  return rows.length === 1;
}

beforeAll(async () => {
  db = await connectPostgres();
}, 120_000);

afterEach(async () => {
  const outbox = outboxIds.splice(0);
  const events = eventIds.splice(0);
  const users = notificationUserIds.splice(0);
  if (outbox.length > 0) {
    await db.delete(moderationOutboxes).where(inArray(moderationOutboxes.id, outbox));
  }
  if (events.length > 0) {
    await db.delete(moderationEvents).where(inArray(moderationEvents.id, events));
  }
  if (users.length > 0) {
    await db.delete(notifications).where(inArray(notifications.oxyUserId, users));
  }
  const paymentOutbox = paymentOutboxIds.splice(0);
  const providerEvents = providerEventIds.splice(0);
  if (paymentOutbox.length > 0) {
    await db.delete(paymentOutboxes).where(inArray(paymentOutboxes.id, paymentOutbox));
  }
  if (providerEvents.length > 0) {
    await db
      .delete(paymentProviderEvents)
      .where(inArray(paymentProviderEvents.providerEventId, providerEvents));
  }
  const guests = guestSessionIds.splice(0);
  if (guests.length > 0) {
    await db.delete(guestSessions).where(inArray(guestSessions.id, guests));
  }
  const touches = touchIds.splice(0);
  if (touches.length > 0) {
    await db.delete(referralTouches).where(inArray(referralTouches.id, touches));
  }
});

afterAll(async () => {
  // The touch fixtures' parent chain, FK order: code → partner → program.
  if (touchChain !== null) {
    await db.delete(referralCodes).where(eq(referralCodes.id, touchChain.codeId));
    await db.delete(referralPartners).where(eq(referralPartners.id, touchChain.partnerId));
    await db.delete(referralPrograms).where(eq(referralPrograms.id, touchChain.programVersionId));
    touchChain = null;
  }
  await closePostgres();
});

describe('the registry the sweeper runs over', () => {
  it('names every table the sweeper is responsible for, and nothing else', () => {
    // The vacuity floor for every case below: a sweep over an empty or shrunken
    // registry deletes nothing, and "the row survived" would then pass for the
    // wrong reason. Pinning the exact set also fails a table added to the
    // registry without a case here, rather than letting it ride untested.
    //
    // Three carried a Mongo TTL index; the payment tables, the referral touch
    // store and guest_sessions were born in Postgres, where there is no TTL
    // index to carry, which is precisely why they need this loop.
    // `guest_sessions` appears TWICE deliberately: a session is purged 7 days
    // after ABSOLUTE expiry or after REVOCATION (ADR 0003 D11), and the
    // registry has no way to express OR — so each trigger is its own target
    // over its own indexed column.
    // The six analytics tables (#77) join them for the same reason the payment
    // ones did: born in Postgres, each carrying its own `expires_at` stamped
    // from the retention class of what it holds. `analytics_pseudonym_salts` is
    // the one worth reading twice — deleting a retired salt is what makes
    // pseudonym rotation irreversible, so an un-swept row silently un-does the
    // domain's central privacy guarantee (data-lifecycle rule 7).
    // #108 adds three: `guest_order_access_grants` (swept on a `purge_at`
    // column the WRITER stamps from the credential's purpose — the
    // `notifications` "make the condition a column" resolution, because the ADR
    // gives exchange rows 24 h and portal rows 90 days and this registry has no
    // filter), `guest_portal_messages`, and `guest_recovery_attempts`. Its
    // other two tables are deliberately NEVER swept: a suppression is a
    // person's request to stop receiving mail and does not expire because they
    // waited, and the operator audit must outlive what it is about.
    expect(EXPIRY_TARGETS.map((target) => getTableName(target.table)).sort()).toEqual([
      'analytics_events',
      'analytics_experiment_exposures',
      'analytics_pseudonym_salts',
      'analytics_query_aggregates',
      'analytics_rollups',
      'analytics_search_queries',
      // #62's rejection RESIDUAL is the only ingestion table with a deadline:
      // it is bounded by traffic, while every other one is bounded by the
      // catalogue and is the audit history a rights suspension must not delete.
      'catalog_source_rejections',
      // #63's THREE, and the split is the retention argument made visible: the
      // per-record ENTRIES expire first (30 days — a merchant downloads them
      // this week, and they are the only #63 table bounded by traffic), the
      // REPORT that counts them outlives them (90 days — an active mapping
      // version cites one by foreign key), and a staged UPLOAD goes soonest of
      // all (7 days — the bytes live on one task's disk and do not survive a
      // deployment, so a long-lived row is a `missing` refusal with a
      // plausible-looking date on it).
      'feed_import_report_entries',
      'feed_import_reports',
      'feed_uploads',
      'guest_order_access_grants',
      // #109's ONE, and the two it leaves out are the point: a claim records
      // who owns a purchase and a revocation records an operator correcting
      // that, so a retention shorter than the orders would answer "who claimed
      // this, and did anyone detach it" with silence. Only the follow-up JOB
      // expires — and what surfaces a stalled dispatcher is the CLAIM, which is
      // retained and still shows in the trace with no eligibility beside it.
      'guest_order_claim_outbox',
      'guest_portal_messages',
      'guest_recovery_attempts',
      'guest_sessions',
      'guest_sessions',
      'moderation_events',
      'moderation_outboxes',
      'notifications',
      // #78's ONE, and the three it leaves out are the point:
      // `offer_price_series`, `offer_price_points` and
      // `offer_price_write_metrics` carry no deadline of their own. Points are
      // removed by CASCADE when the observation they cite is, which is what
      // keeps "every point traces to an immutable observation" true at every
      // instant rather than true until a sweep; a series is one row per
      // question anybody asked; and the metrics are the counters that make a
      // broken dedup visible, which is exactly what must not quietly age out.
      'offer_price_snapshots',
      'payment_outboxes',
      'payment_provider_events',
      // #124's two, and the FIVE it deliberately leaves out are the point:
      // `supplier_order_attempts`, `purchase_order_line_outcomes`,
      // `purchase_order_tracking_events`, `purchase_order_documents` and
      // `procurement_exceptions` carry no deadline, because they are the
      // evidence that a supplier order was placed, what it cost and what
      // happened to it — bounded by the number of purchase orders rather than
      // by traffic, and read during a chargeback months later.
      'procurement_outboxes',
      'referral_touches',
      // #95's two query-side tables. A session is one shopper's bounded
      // clarification conversation and a turn holds #77's REDACTED query form,
      // so for the turn the sweep IS the erasure — which is why neither table
      // has an append-only trigger: one refusing DELETE would make the
      // retention this domain most needs fail silently.
      'search_intent_sessions',
      'search_intent_turns',
      'supplier_provider_events',
      // #81's ONE, and the three it leaves out are the point: a watchlist and
      // its items are a person's own data, removed when THEY remove them, and a
      // snapshot's LINES cascade with the snapshot — so a line can never
      // outlive the evaluation it describes and the sweep never has to know
      // they exist. Only the recorded evaluation has a deadline, because it is
      // the only table here whose size is a function of how often somebody
      // opens a list.
      'watchlist_snapshots',
    ]);
  });

  it('gives every target a reason, since a registry entry authorises a DELETE', () => {
    for (const target of EXPIRY_TARGETS) {
      expect(target.reason.length, `${getTableName(target.table)} has no reason`).toBeGreaterThan(0);
    }
  });
});

describe('sweepExpiredRowsOnce — the tick the scheduler runs', () => {
  it('reaps an expired outbox row and leaves one whose deadline has not passed', async () => {
    const expired = await makeOutboxRow(EXPIRED_AT);
    const live = await makeOutboxRow(NOT_YET_EXPIRED_AT);

    await sweepExpiredRowsOnce();

    expect(await outboxExists(expired), 'the expired outbox row survived').toBe(false);
    expect(await outboxExists(live), 'a live outbox row was reaped').toBe(true);
  });

  it('reaps an expired webhook dedupe claim and leaves a live one', async () => {
    const expired = await makeEventClaim(EXPIRED_AT);
    const live = await makeEventClaim(NOT_YET_EXPIRED_AT);

    await sweepExpiredRowsOnce();

    expect(await eventExists(expired), 'the expired claim survived').toBe(false);
    // A claim must outlive every redelivery of its event; reaping one early
    // lets a duplicate decision be processed a second time.
    expect(await eventExists(live), 'a live dedupe claim was reaped').toBe(true);
  });

  it('reaps a long-dismissed notification and leaves an undismissed one', async () => {
    const dismissed = await makeNotification(PAST_NOTIFICATION_RETENTION);
    const neverDismissed = await makeNotification(null);

    await sweepExpiredRowsOnce();

    expect(await notificationExists(dismissed), 'the dismissed notification survived').toBe(false);
    expect(await notificationExists(neverDismissed), 'an undismissed notification was reaped').toBe(
      true,
    );
  });

  it('reaps an expired payment outbox row and leaves one whose deadline has not passed', async () => {
    const expired = await makePaymentOutboxRow(EXPIRED_AT);
    const live = await makePaymentOutboxRow(NOT_YET_EXPIRED_AT);

    await sweepExpiredRowsOnce();

    expect(await paymentOutboxExists(expired), 'the expired payment event survived').toBe(false);
    expect(await paymentOutboxExists(live), 'a live payment event was reaped').toBe(true);
  });

  it('reaps an expired provider-event dedupe row and leaves a live one', async () => {
    const expired = await makeProviderEventRow(EXPIRED_AT);
    const live = await makeProviderEventRow(NOT_YET_EXPIRED_AT);

    await sweepExpiredRowsOnce();

    expect(await providerEventExists(expired), 'the expired provider event survived').toBe(false);
    // Same reasoning as the moderation dedupe claim above: the row must outlive
    // every redelivery of its event, or a duplicate charge notification is
    // applied a second time.
    expect(await providerEventExists(live), 'a live provider event was reaped').toBe(true);
  });

  it('reaps a guest session 8 days past ABSOLUTE expiry, not one inside the purge grace', async () => {
    // The pair spans the grace boundary, not just expired-vs-live: an expired
    // session inside the 7-day window must SURVIVE this tick (D11 keeps it as
    // forensic headroom), so `DELETE WHERE expires_at <= now()` — expiry
    // without the grace — fails here even though every row is "expired".
    const pastGrace = await makeGuestSessionRow({ expiresAt: PAST_GUEST_PURGE_GRACE });
    const insideGrace = await makeGuestSessionRow({ expiresAt: WITHIN_GUEST_PURGE_GRACE });
    const live = await makeGuestSessionRow({ expiresAt: NOT_YET_EXPIRED_AT });

    await sweepExpiredRowsOnce();

    expect(await guestSessionExists(pastGrace), 'the purge-due session survived').toBe(false);
    expect(await guestSessionExists(insideGrace), 'a session inside the grace was reaped').toBe(
      true,
    );
    expect(await guestSessionExists(live), 'a live session was reaped').toBe(true);
  });

  it('reaps a guest session 8 days after REVOCATION even though its expiry is far off', async () => {
    // The second guest target's own distinction: revocation purges on its own
    // clock, independent of `expires_at` — a revoked session must not linger
    // for the remaining ~90 days of its absolute window.
    const revokedPastGrace = await makeGuestSessionRow({
      expiresAt: NOT_YET_EXPIRED_AT,
      revokedAt: PAST_GUEST_PURGE_GRACE,
    });
    const revokedInsideGrace = await makeGuestSessionRow({
      expiresAt: NOT_YET_EXPIRED_AT,
      revokedAt: WITHIN_GUEST_PURGE_GRACE,
    });

    await sweepExpiredRowsOnce();

    expect(
      await guestSessionExists(revokedPastGrace),
      'the long-revoked session survived',
    ).toBe(false);
    expect(
      await guestSessionExists(revokedInsideGrace),
      'a freshly revoked session was reaped',
    ).toBe(true);
  });

  it('reaps a touch past its retention and leaves one still inside it', async () => {
    // The #142 privacy contract's mechanical half: raw touch evidence leaves
    // on its own clock, separately from the durable attributions derived from
    // it. Nothing else deletes a touch.
    const expired = await makeReferralTouchRow(EXPIRED_AT);
    const live = await makeReferralTouchRow(NOT_YET_EXPIRED_AT);

    await sweepExpiredRowsOnce();

    expect(await touchExists(expired), 'the expired touch survived').toBe(false);
    expect(await touchExists(live), 'a live touch was reaped').toBe(true);
  });

  it('covers every target in ONE tick, not just the first', async () => {
    // The case the per-target cases above cannot make between them: each passes if the
    // sweep runs only its own target. Seeding one doomed row per table and
    // sweeping once is what proves the loop does not stop early — which is
    // exactly what a `return` in place of a `continue`, or a sweep of
    // `EXPIRY_TARGETS[0]`, would do.
    const outbox = await makeOutboxRow(EXPIRED_AT);
    const event = await makeEventClaim(EXPIRED_AT);
    const notification = await makeNotification(PAST_NOTIFICATION_RETENTION);
    const paymentOutbox = await makePaymentOutboxRow(EXPIRED_AT);
    const providerEvent = await makeProviderEventRow(EXPIRED_AT);
    const expiredGuest = await makeGuestSessionRow({ expiresAt: PAST_GUEST_PURGE_GRACE });
    const revokedGuest = await makeGuestSessionRow({
      expiresAt: NOT_YET_EXPIRED_AT,
      revokedAt: PAST_GUEST_PURGE_GRACE,
    });
    const touch = await makeReferralTouchRow(EXPIRED_AT);

    await sweepExpiredRowsOnce();

    expect(await outboxExists(outbox)).toBe(false);
    expect(await eventExists(event)).toBe(false);
    expect(await notificationExists(notification)).toBe(false);
    expect(await paymentOutboxExists(paymentOutbox)).toBe(false);
    expect(await providerEventExists(providerEvent)).toBe(false);
    expect(await guestSessionExists(expiredGuest)).toBe(false);
    expect(await guestSessionExists(revokedGuest)).toBe(false);
    expect(await touchExists(touch)).toBe(false);
  });
});
